### ISSUE TITLE
determine and set reasonable limits on roche parameters

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#100]
limits on q, F, d, etc based on the limits of libphoebe and marching.

**Comment by kecnry** [comment]
@horvatm - is it safe to say we've decided not to go in this direction?  If so, feel free to close.

**Comment by horvatm** [comment]
Closing remark: The best way to handle ranges of parameters is to make good exceptions. For that we need users that encounter problematic ranges of parameters. These instances can be then studied. For some ranges we will find how to handle them and for others we raise exceptions, or return some errors or at least give warnings to indicate that perhaps something is not go as planned. With each month of use we find more pathological cases, e.g. near to contact, near to overflow etc, and I am confident that in time we could resolve most of them. At the moment, we are still very green behind the ears about what can fail.
