### ISSUE TITLE
smarter parameter for delta in marching

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#101]
preferably based on estimated precision (in flux) if possible, or number of triangles.

right now, its difficult to set a reasonable default for delta that gives decent precision for all cases but avoids getting terribly expensive.

**Comment by horvatm** [comment]
I have two ideas:

We could have estimated number of triangles: 
```
  N_{estimate} = 4 A/(sqrt(3) delta^2)
```
We could have target precision of the flux in LC curves
```  
  dL/L
```
We could estimate dL/L using different number of triangles. I guess we could estimate
```
L = L_{exact} + O(N^{-p}) 
```
where p is probably  p = 0.5, 1, 2.

**Comment by kecnry** [comment]
@aprsa - is there a robust way to translate ntriangles (or nelements) into gridsize for WD-style and the legacy wrapper?  It would be nice to unify and handle the translation rather than expose two different sets of options.

**Comment by kecnry** [comment]
also: does anyone have an opinion on what default we should use for ntriangles?  I currently have it set at ntriangles=1000, but I believe that is more course in most cases than our previous default of delta=0.1.

**Comment by horvatm** [comment]
I like ntriangles =1000, as this already enough to get some solid results.

**Comment by aprsa** [comment]
Not trivially. N to Ntriangles goes directly, but to go the other way, we
either need to iterate or have a lookup table.

**Comment by kecnry** [comment]
ok, gridsize (N) to Ntriangles will still be very helpful, as I need it for the legacy importer.  For now I'll leave gridsize for WD meshes and the legacy wrapper - we can revisit that later.

**Comment by aprsa** [comment]
Done by commit 375a29f008efba41a446906046a75f667f424c17￼.
