### ISSUE TITLE
Reflection for rotating stars is not working

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#102]
To reproduce:

import phoebe
import numpy as np

b = phoebe.default_binary()

b.set_value('rpole', component='primary', value=1.8)
b.set_value('rpole', component='secondary', value=0.96)

b.set_value('teff', component='primary', value=10000)  # A0
b.set_value('teff', component='secondary', value=5200) # K0

b.set_value('q', component='binary', value=0.96/1.8)

b.add_dataset('lc', passband='Johnson:V', intens_weighting='photon', dataset='data')

b.add_compute(compute='baseline',      distortion_method='rotstar', reflection_method='none',   boosting_method='none')
b.add_compute(compute='refl_only',     distortion_method='rotstar', reflection_method='wilson', boosting_method='none')

period = 1.0
b.set_value('sma', component='binary', value=5.90301859677)

# set the timestamp that corresponds to quarter-phase
b.set_value('period', component='binary', value=period)
b.set_value('times', dataset='data', context='dataset', value=[0.25*period])

b.run_compute(compute='baseline', model='baseline_model')
b.run_compute(compute='refl_only', model='reflection_model')
    
baseline_flux      = b.get_value('fluxes', model='baseline_model')[0]
refl_only_flux     = b.get_value('fluxes', model='reflection_model')[0]
    
refl_amp  = refl_only_flux / baseline_flux
print refl_amp # should NOT be 1.0

**Comment by kecnry** [comment]
fixed by setting albedo
