### ISSUE TITLE
Implement reddening due to interstellar extinction and atmosphere

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#105]

**Comment by kecnry** [comment]
also need to consider the 'ie' switch in the legacy wrapper - may need to either be renamed or removed and pull from the system parameters that handle extinction.

**Comment by aprsa** [comment]
this needs some thought to be done correctly, most likely by expanding the passband files. Deferring to the next version.

**Comment by kecnry** [comment]
this is currently under development in the 'Extinction' branch and planned for an upcoming feature release.
