### ISSUE TITLE
fix and test limb-darkening

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#108]

**Comment by aprsa** [comment]
Fixed for analytical LDs with df0e74188a952e0b4ed1fb703b9c5041cba1e081.

**Comment by kecnry** [comment]
waiting on #111 and #112 before able to fully test

**Comment by aprsa** [comment]
Fixed all remaining issues with 315c7911e88bde0d97fa0574998004507dca3558. After nosetests pass, @kecnry should close this bug.
