### ISSUE TITLE
system checks for ld_coeffs

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#115]
sum of coeffs for linear, power, logarithmic < 1
each coeffs should be positive
etc

**Comment by horvatm** [comment]
You can use for this:

/*
  C++ wrapper for Python code:

    Check the parameters of the particular limb darkening model

  Python:

    value = ld_check(descr, params)

  with arguments

    descr: string (bytes)
          supported ld models:
            "uniform"     0 parameters
            "linear"      1 parameters
            "quadratic"   2 parameters
            "nonlinear"   3 parameters
            "logarithmic" 2 parameters
            "square_root" 2 parameters
            "power"       4 parameters

    params: 1-rank numpy array of float

  Return:
    true: if parameters pass the checks, false otherwise
*/

static PyObject *ld_check(PyObject *self, PyObject *args, PyObject *keywds)
