### ISSUE TITLE
Convergence to the point on horizon failed

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#126]
The following code fails with the above message:

import phoebe
from phoebe import u, c
import numpy as np

b = phoebe.Bundle.default_binary()

b.add_compute(compute='phoebe', maxpoints=10000000)

pb = 'Bolometric:1760-40000'
b.add_dataset('lc', times=[0.75,], dataset='lc01', passband=pb)

# The Sun-Earth system

b['pblum@primary'] = 1.*u.solLum
b['teff@primary'] = 1.*u.solTeff
b['rpole@primary'] = 1*u.solRad
b['syncpar@primary'] = 14.61

b['period@orbit'] = 1.*u.yr
b['q@orbit'] = 3.986004e14/1.3271244e20   # (GM)_E / (GM)_Sun
b['sma@orbit'] = 1.*u.au

b['teff@secondary'] = (300, 'K')
b['rpole@secondary'] = 1.*c.R_earth
b['syncpar@secondary'] = 365.25

b.set_value_all('atm', value='blackbody')
b.set_value_all('ld_func', value='linear')
b.set_value_all('ld_coeffs', value=[0.0])

b['distance@system'] = (1, 'au')

b.run_compute(compute='phoebe', delta=0.17, protomesh=True, pbmesh=True)

**Comment by horvatm** [comment]
I can fixed that, i think. 

But seriously, who need to know analytic horizon at every step. Actually, i can not find a single computation which directly depends on this. It is an extreme waste of computational time. This needs to be shut off by default, as I already said! @kecnry

**Comment by aprsa** [comment]
There should probably be a separate switch for computing horizons when
pbmesh=True, but either way it shouldn't fail.

**Comment by horvatm** [comment]
Parameters at which it fails:

Omega0=3.5640087276485906e+05
q=3.3294607832806988e+05
F=3.6525000000000000e+02
d=1.0000000000000000e+00

These are internal data:

Hessian=
4.2738362765634760e+18	-4.9678290715475061e+11	-5.8482048930493629e-15
-4.9678290715475061e+11	4.2737977802339891e+18	-4.5326018799829336e-13
-5.8482048930493629e-15	-4.5326018799829336e-13	-4.2738363273918915e+18

-grad Omega=
-7.0484760537585579e+06	-5.4628623480204368e+08	-6.4532959899430479e-18	

Omega0-Omega=
5.8207660913467407e-11

view=
9.9991677270219526e-01	-1.2901459949419714e-02	-6.1232339957367660e-17

matrix A=
2.9847833134887398e+17	2.3552109696316867e+18
2.3552109696316867e+18	1.8265676573658472e+37

remainders =
-5.8207660913467407e-11	-5.5107489787042141e-01

det=5.4519086646637990e+54

solutions =
-1.9501469530253844e-28	-3.0169969077731491e-38

point_on_horizon:
-5.5100807804962308e-07	-4.2705416385729978e-05	-5.0274263418631569e-31
