### ISSUE TITLE
Need to synchronize names for LD models in libphoebe, *.py code and article

### ISSUE THREAD

**Issue by horvatm** [phoebe-project/phoebe2#128]
We need to synchronize names for LD models in libphoebe, *.py code and article. 
In ld_models.h we currently have:

```
case UNIFORM: return 1;
case LINEAR:  return 1 - p[0]*(1 - mu);
case QUADRATIC: return 1 - (1 - mu)*(p[0] + (1 - mu)*p[1]);
case NONLINEAR: return 1 - p[0]*(1 - mu) - p[1]*std::pow(1 - mu, p[2]);
case LOGARITHMIC: return 1 - p[0]*(1 - mu) - p[1]*mu*std::log(mu);
case SQUARE_ROOT: return 1 - p[0]*(1 - mu) - p[1]*(1- std::sqrt(mu));
```

In the paper we have 

\begin{tabular}{ll}
$\frac{I}{I_0} = 1 - x_\lambda (1-\mu)$ & linear model \
$\frac{I}{I_0} = 1 - x_\lambda (1-\mu) - y_\lambda \mu \log_{10} \mu$ & logarithmic model \
$\frac{I}{I_0} = 1 - x_\lambda (1-\mu) - y_\lambda (1-\sqrt{\mu})$ & square  model \
$\frac{I}{I_0} = 1 - x_\lambda (1-\mu) - y_\lambda (1-\mu)^2$ & quadratic model \
$\frac{I}{I_0} = 1 - c_{1,\lambda} (1 - \mu^{\frac{1}{2}}) - c_{2,\lambda} (1-\mu) -c_{3,\lambda}(1-\mu^{\frac{3}{2}}) - c_{4,\lambda} (1-\mu^2)$ & power model \
\end{tabular}

So which models we support and how do we name them? @kecnry @aprsa

**Comment by kecnry** [comment]
@horvatm - is this safe to close?

**Comment by horvatm** [comment]
Currently we have in ld_models.h these models:
  * 'uniform': D(mu) = 1
  * 'linear':  D(mu) = 1 - x*(1 - mu)
  * 'quadratic': D(mu) = 1 - x(1 - mu) - y(1 - mu)^2 
  * 'nonlinear': D(mu) = 1 - x(1 - mu) - y (1 - mu)^p
  * 'logarithmic': D(mu) = 1 - x*(1-mu) - y*mu*log(mu)
  * 'square_root': D(mu) = 1 - x(1 - mu) - y(1 - sqrt(mu))
  * 'power': many times called claret: 
      D(mu) = 1 - a0(1 - mu^(1/2)) - a1(1 - mu) - a2(1-mu^(3/2)) - a3(1 - mu^2)

Can @kecnry and @aprsa  check that we use the same strings and formulas in passbands.py?

**Comment by horvatm** [comment]
Currently we have these in passbands.py:

        if ld_func == 'linear':
            return ld_coeffs[0:1]
        if ld_func == 'logarithmic':
            return ld_coeffs[1:3]
        if ld_func == 'square_root':
            return ld_coeffs[3:5]
        if ld_func == 'quadratic':
            return ld_coeffs[5:7]
        if ld_func == 'power':
            return ld_coeffs[7:11]

So only uniform is missing, but this is achieved by linear and taking parameter x=0. So I will close this issue.
