### ISSUE TITLE
host atmosphere tables to download

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#134]
only include most basic atmosphere tables in source but allow for an easy interface to download and "install" additional tables.  Atmosphere tables are currently 139 of 141 MB.

**Comment by aprsa** [comment]
We should decide what atmospheres are deemed "core". Perhaps only Johnson V
should be included if the interface is streamlined enough to handle
automatic downloads at execution time.

**Comment by kecnry** [comment]
ok, I can play with the interface to handle downloads.  This is what I have in mind, let me know if you have any comments/suggestions or had something else in mind.

```
>>> print b['passband'].choices
['Johnson:V']
>>> phoebe.list_available_passbands()
['Johnson:B', 'Johnson:I', ...]
>>> phoebe.download_passband('Johnson:B')
>>> print b['passband'].choices
['Johnson:V', 'Johnson:B']
# this may actually be tough to get the choices to update immediately, but I can try
>>> b.set_value('passband', 'Johnson:I')
# this will only work if online and the passband is valid
INFO: attempting to download/install Johnson:I
>>> b.set_value('passband', 'not_in_list_available_passbands')
# this raises an error since not in phoebe.list_available_passbands()
ValueError: not a valid choice
```

**Comment by kecnry** [comment]
please see the commit above and the 'passband_download' branch - I managed to implement the above with only a few changes

```
>>> phoebe.list_installed_passbands()
['Johnson:V']
>>> phoebe.list_online_passbands()
['Johnson:B', ...]
>>> phoebe.list_passbands()
# lists online AND installed
['Johnson:V', 'Johnson:B', ...]
>>> print b['passband'].choices
# last cached version of list_passbands()
['Johnson:V', 'Johnson:B']
>>> phoebe.download_passband('Johnson:B')
# downloads, installs, AND initializes
>>> b.set_value('passband', 'Johnson:I')
# since Johnson:I isn't installed but is available online, it is downloaded, installed, initialized
>>> b.set_value('passband', 'not_in_list_available_passbands')
ValueError: value must be one of [choices]
```

The tables themselves are now stored in https://github.com/phoebe-project/phoebe2-tables with a subdirectory depending on the version of phoebe.  This way if we change the format of the tables to support a new feature, we can still support old formats for previous versions.  And likewise, we can add support for new passbands to old version of phoebe easily.

We also need to consider a flag to setup.py which will clear the passband installations - this will be particularly useful for any changes in passband versions so we don't have to keep doing fresh installs.

Anyone who is interested - please try this and make sure it works.  Download and install this branch, delete your locally installed passbands or do a fresh install, and make sure everything works as expected.  Once tests pass and I hear no objections, I'll go ahead and merge into development.

**Comment by aprsa** [comment]
> The tables themselves are now stored in
> https://github.com/phoebe-project/phoebe2-tables with a subdirectory
> depending on the version of phoebe.  This way if we change the format
> of the tables to support a new feature, we can still support old
> formats for previous versions.  And likewise, we can add support for
> new passbands to old version of phoebe easily.

The way I wrote the tables, they will always be backwards *and*
forwards compatible. The core changed a few times, that is why we
needed to remove the build directories and such, but all of that is
stable now and I don't expect any major changes. That said, versioning
is still a good idea simply to keep a tab on table contents.

**Comment by kecnry** [comment]
this has now been merged into development
