### ISSUE TITLE
separate docs into separate repo?

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#135]
docs are currently 37 MB (phoebe itself is 141 MB, 139 of which are atmosphere tables - see also #134).

The docs directory is so large because the .ipynb files include all created images/animations.  We could easily separate them into a phoebe2-docs repository and tag each release to match those in the phoebe2 repository.

**Comment by horvatm** [comment]
To me, this sounds meaningful.

**Comment by kecnry** [comment]
done.  The [phoebe2-docs repository](http://github.com/phoebe-project/phoebe2-docs) will have the same basic branching structure and this repositoy.  With a master-branch which holds the releases (tagged with thte same version as phoebe releases) and a development-branch which should be kept up-to-date.

Temporary feature-branches don't necessarily need to have branches in the phoebe2-docs repository, but if they do should be merged at the same time as here.
