### ISSUE TITLE
disable interactive mode temporarily during from_legacy

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#163]
if interactive mode is enabled, then disable at start of from_legacy and re-enable after.  This way checks aren't constantly run.  Need to be careful to make sure this works well with constraint logic within from_legacy

**Comment by bpablo** [comment]
What is interactive mode?

**Comment by kecnry** [comment]
When interactive mode is off, constraints and system checks are deferred until requested or run_compute is called. The legacy import is slow mainly because of these two things.

**Comment by kecnry** [comment]
closed by d074bcd2159c2edd784a26df002c521533245099 and 364d9bf41f801f8d52ce8ea6011c3f5cd194f344
