### ISSUE TITLE
Webpage documentation for testing incomplete

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#165]
We should add all pieces of code that need to be installed (i.e. phoebe legacy, photodynam, ......) and explain what is happening, what is expected, etc.

**Comment by kecnry** [comment]
this should all be included now on the website here: http://phoebe-project.org/contribute#testing.  Andrej can you check and see if we can close this now?

**Comment by aprsa** [comment]
Looks good to me!
