### ISSUE TITLE
boosting/beaming support

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#17]

**Comment by aprsa** [comment]
Preliminary support for linear corrections based on Imus implemented in the boosting branch (public). The equation differs from Steven's so we need to get to the bottom of the discrepancy. The table is being computed for Johnson V and will be done in a few hours.

**Comment by kecnry** [comment]
As for implementation in the frontend - we used to have different boosting methods in alpha (simple, local, global).  Is this something we'll still have or will boosting be toggled with a single boolean switch (ie boosting=True/False in the compute options)?

**Comment by aprsa** [comment]
For beta we should only have boosting=True/False.

**Comment by aprsa** [comment]
The treatment of boosting the way I implemented it yesterday is already better than global, but it doesn't account for the changing slope in broad passbands.

**Comment by kecnry** [comment]
Do we think we'll have other methods in the future?  If so, I think we should have a boosting_method with choices ['none', 'something'] rather than have to make parameter changes down the road.

**Comment by aprsa** [comment]
I'm pretty sure we will have better options in the future. A choice parameter works for me.

**Comment by aprsa** [comment]
Tested for KOI-74 and theoretical models.
