### ISSUE TITLE
Incorrect computation of photon-weighted intensity when ck2004 with interp and reflection is used

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#177]
All other combinations give reasonable values, i.e. 'blackbody' or 'ck2004' with 'quadratic' and photon_weighted=True or False, but 'ck2004' with 'interp' and photon_weighted=True does not return correct values. The tables seem correct, so there has to be something causing Imu to assume unphysical values.

**Comment by horvatm** [comment]
Where do you suspect is the problem?

**Comment by aprsa** [comment]
I checked Imu for sanity and it seemed ok; I also checked the tables and they seem ok. I would try to look for the problem as reflection modifies Teffs and passes them to Imu. I will prepare a demonstration of the problem at some point soon.

**Comment by aprsa** [comment]
Fixed with commit 3f08bbeba8209e34359f1180bb70b44a36dadf8f.
