### ISSUE TITLE
phoebe.atmospheres.limbdark.download_spectra()

### ISSUE THREAD

**Issue by tianzhijia** [phoebe-project/phoebe2#178]
I installed phoebe2 through `sudo -H pip install phoebe`.
When I tried the command:
`phoebe.atmospheres.limbdark.download_spectra()`
It shows that 

> Downloading/copying http://www.phoebe-project.org/docs/auxil/spectra.tar.gz to destination folder /Library/Python/2.7/site-packages/phoebe/atmospheres/tables/spectra
> Estimated size: 1.3 GB (can take a while!)
> Downloaded tar archive from phoebe-project.org
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Python/2.7/site-packages/phoebe/atmospheres/limbdark.py", line 3484, in download_spectra
>     force=force, estimated_size='1.3 GB (can take a while!)')
>   File "/Library/Python/2.7/site-packages/phoebe/atmospheres/limbdark.py", line 3511, in download
>     tar = tarfile.open(destin)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1672, in open
>     raise ReadError("file could not be opened successfully")
> tarfile.ReadError: file could not be opened successfully

and then I noticed that line 3484 in download_spectra quote the website

> 'http://www.phoebe-project.org/docs/auxil/spectra.tar.gz'

I tried the website through safari, and the page not found,

> The requested URL /docs/auxil/spectra.tar.gz/ was not found on this server.

Is there another website to download spectra?
Similar, the problem happens when `phoebe.download_atm()`

I'm familiar with IDL, but a new pythoner.
Thx

**Comment by kecnry** [comment]
pip has an older version of phoebe (2.0-alpha - we'll update it with the official 2.0-release in a month or so).  If you'd like to try the 2.0-beta version, you'll need to download and install directly from github.  Only the alpha version used phoebe.download_atm() and since it is no longer supported and has been completely rewritten for beta, those sources are no longer available.
