### ISSUE TITLE
osx tests timeout on travis (currently only test for build success)

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#183]
seems to be due to a change with the travis osx systems, not phoebe itself - but this still needs to be fixed so that we can test on osx. 

See the travis_osx_build branch - will merge into development once the problem is tracked down and fixed.

**Comment by horvatm** [comment]
This seems to be fixed now. Please merge corrections in .travis.yml with the development branch. Do we need to test is phoebe 1 also compiles with clang?

**Comment by kecnry** [comment]
closed by c55bfd2f672c7e91e63ead67827f2e4aa36b9008

**Comment by kecnry** [comment]
note: travis was still timing-out during some tests (probably just slower on macs).  For now we will just test to make sure the build succeeds, but in the future may want to re-implement full testing on osx

**Comment by kecnry** [comment]
travis has been replaced with GitHub actions (with successful mac CI testing)
