### ISSUE TITLE
animate() ignores user-defined limits

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#189]
Problem: to maintain the correct aspect ratio, fixed_limits needs to be True and set_aspect('equal') needs to be used. This in turn changes the size of the axes, so multi-axes plots look poorly. It would be much better if we could change the limits on particular axes so that, instead of the box itself, it is padding that accounts for equal aspect, i.e. setting adjustable='datalim'.

Solution: we can either do this under the hood (preferred), or by passing xlim and ylim to animate(). The latter is a bit hacky and it leaves it up to the user to figure out padding, but it's probably faster to implement.

Since @kecnry already has a TODO in the code for this, I'm assigning this to him. :)

**Comment by kecnry** [comment]
fixed with autofig integration
