### ISSUE TITLE
redistribution is not supported for contact binaries (and won't be)

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#192]
... but we can and do support reflection.  The problem is that in the redistribution framework, the constraint requires all incident flux to be accounted for by reflection or redistribution (ie. we got rid of the "lost bucket").

Note: this is currently causing an error in the nosetests for the redistribution branch, so must be fixed before being merged into development or released.

Proposed solution:
* implement a system check that will complain if any of the redistribution fractions are non-zero and the system is a contact binary.  As with all system checks, this would throw warnings until run_compute, at which time it would throw an error.
* Warning text would advise the user to either set reflection fraction to 1, or to manually break the redistribution constraint - effectively allowing for a "lost bucket"
* in the backend: if the body is an envelope, fall-back onto reflection only (no redistribution).
* in the nosetest: break the redistribution constraint to allow looping over albedos (reflection fractions)

@aprsa - any thoughts/comments/objections before we go ahead on this?

**Comment by horvatm** [comment]
I found a way to define it local and uniform redistribution. It is already in the paper and waits for implementation.

**Comment by kecnry** [comment]
marking this as "wontfix" for now since we don't have (immediate) plans to officially support redistribution in a release
