### ISSUE TITLE
support for l3 in percent of total light

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#204]
where l3perc = l3 / [(L1+L2)/4pi + l3] with L1 and L2 being computed passband luminosities at t0.

Once this is in place, @bpablo will need to update the  legacy importer and wrapper (currently raises a warning an ignores l3 if given in % of total light).

**Comment by aprsa** [comment]
Any chance we could label them something shorter, i.e. just "fraction" instead of "fraction of total light"? Or at least put underscores in there?
