### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by bsipocz** [phoebe-project/phoebe2#21]
@kecnry - Great to see that you made the move to GH.

How long does it take to run the tests locally? I wonder whether you plan to set up to run the them on any CI platform? I can't remember whether we talked about it while you were here on the binary conference.

If it's yes for CI, then we have a [helpers package](https://github.com/astropy/ci-helpers) that you may be interested in using. It basically takes care of installing the dependencies and setting up the conda environment. If there is any infrastructural issues upstream due to new package versions, we try to fix those in there relatively quickly. Currently we support Linux/OSX with travis and windows with appveyor.

However I have to admit that you may run into limitations as we mainly have pure python/cython packages. 

Needless to say I'm happy to help to set this up.

**Comment by kecnry** [comment]
@bsipocz - we're still working on building out the whole suite of science tests for the upcoming beta release, so I don't have a good feel for this yet.  As of now we're still manually running the tests, but will surely want some sort of automated testing down the road, so we'll definitely keep this in mind and I'll make sure to reach out to you if we decide to go in this direction.  Thanks!
