### ISSUE TITLE
raise error if number of returned triangles not within 20%

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#218]
so that computations don't continue with a probably flawed mesh

**Comment by kecnry** [comment]
We do currently handle this within the backend by setting max_triangles=ntriangles*2.  @horvatm - do you think this should be lowered to 1.2?

Alternatively, we could allow the computation to continue and raise a warning in the frontend.  But this will require some paperwork for the cases where the mesh isn't being exposed.

**Comment by horvatm** [comment]
I think 20% is to optimistic. We could lower the limit to 50%.
