### ISSUE TITLE
support spots on single stars

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#222]
Currently, as of the fix to corotate spots (d4edf2db1d56d94b7451836850e569ed665248b8 and #210), spots will fail on run_compute if attached to a single star, because they cannot access the parent orbit.  In order to handle the proper placement of spots on a single star we must decide how we should define longitude (at t0).  The simplest solution would probably be pointing along the global x ("right" on plane-of-sky).  @aprsa - any objections?

Once that is decided, we need to handle the corotation of spots on a single star based on the rotation period, rather than syncpar as is done for stars in orbits.

**Comment by aprsa** [comment]
No objections, that sounds good to me.

**Comment by kecnry** [comment]
I'm glad you didn't object - but then we objected with ourselves and decided it makes more sense to have longitude of 0 pointing towards earth so that the defaults (longitude, t0, etc) result in a minimum at phase=time=0.

I just need to test more thoroughly, include all of these definitions in the docs, and can then get ready for the patch release.
