### ISSUE TITLE
Distinguish Roche coordinate names from POS coordinate names

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#226]
Currently, both Roche and Plane-of-Sky (POS) coordinates are called xs, ys and zs. In protomesh, these are Roche coordinates, while in pbmesh these are POS coordinates. Traditionally in the literature, xyz are used for Roche and uvw are used for POS.

We cannot change the names of arrays because that breaks backwards compatibility. The one option would be to add aliases to POS coordinates (i.e. in the protomesh) that would be called us, vs, ws. Another option would be to do something similar for Roche coordinates (say, xis, etas, zetas). Either way, we need to come up with a straight-forward way to distinguish between coordinate systems.

**Comment by kecnry** [comment]
Summarizing the discussion at today's telecon, we have a few options:

1. Alias parameters to support two sets of names for POS coordinates (xyz and uvw) until future notice (Andrej's favorite, Kyle's least favorite)
2. Break backwards compatibility and rename parameters in the next minor release, including explanation in the release notes.
3. Keep POS coordinates x,y,z but no longer expose the protomesh.  Instead we can have an option to skip passband computations allowing a quick rendering of the mesh at *any time* (as opposed to just t0 currently supported for protomeshes) and in the POS coordinates.  This would also work with future plans to allow exposing/hiding various columns in the mesh - allowing a switch to expose the roche coordinates (i.e. roche_xs, roche_ys) if desired.
4. (technically not mentioned at the telecon, but thought I'd include for completeness) Leave parameter names as-is but clarify in the descriptions and during plotting.  Default axes labels could use u,v,w for POS and clarify units for roche coordinates (i.e. x [roche units] or x [separation]).  We already have the infrastructure in place to complain when parameters with different units are plotted on the same axes, so we could extend this to make a more comprehensible message when a user attempts to plot POS and roche on the same axes.


This isn't an urgent fix and would be a large change for a patch release, so we've decided to deal with it in the misalignment feature release (likely 2.1 or 2.2).
