### ISSUE TITLE
Implementing curvature depending offsetting

### ISSUE THREAD

**Issue by horvatm** [phoebe-project/phoebe2#23]
Implementing curvature depending offsetting of the triangular mesh to enable this feature also for non-convex bodies.

**Comment by horvatm** [comment]
To enable curvature depending offseting do:

dict = mesh_offseting(A, V, NatV, T, curvature="True")

**Comment by kecnry** [comment]
see commits https://github.com/phoebe-project/phoebe2/commit/20b500486364d24501e019f26c8e26f6dd0d622a https://github.com/phoebe-project/phoebe2/commit/3cef8a556b4e549b184356412687632dd7140dc7 https://github.com/phoebe-project/phoebe2/commit/37982bc776a0c54179244811fc06ecb9e00b8dbb https://github.com/phoebe-project/phoebe2/commit/e1ff0dafa932bd8b3c628e3ab5e4c506ca75c9fb

Here is an example of the horizon of a fairly-distorted roche star at quarter phase in plane-of-sky polar coordinates (theta=0 is the "nose").  The black curves are the residuals between the rho of the surface elements and the analytic horizon.  

Without curvature-dependent offsetting, you can see that the nose fails to offset enough (rho is too small) and over-compensates in areas with flatter curvature:
![horizon_curv_resid_3_false](https://cloud.githubusercontent.com/assets/877591/18217713/7a2db8e2-712c-11e6-8296-d7c2b6304d4b.png)

With curvature-dependent offsetting, you can see that the residuals are more symmetric and have less systematics:
![horizon_curv_resid_3_true](https://cloud.githubusercontent.com/assets/877591/18217714/7a2df3d4-712c-11e6-8a0f-484bd4f356ba.png)

In the future we could perhaps improve the algorithm to perform better, and could also skip this step for stars which we know are approximately spherical, but for now let's mark this as implemented and closed.
