### ISSUE TITLE
Morphology constraints not imposed when importing from legacy

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#236]
When morphology is non-detached, i.e. semi-detached with secondary filling the Roche lobe, phoebe 1 parameter file does /not/ save the value of the secondary potential because it depends on q, F, and e. Instead, it computes it on the fly. When phoebe2 imports such a file, it sets the potential to whatever is in the parameter file, which is incorrect. What needs to happen is we need to check the morphology constraint and then, during import, compute the critical values of the potential and use those instead.

**Comment by kecnry** [comment]
the 2.0.5 release will include support for semi-detached constraints, with importing/exporting to/from phoebe1 fixed in afbe96724510c7d46759c4f326c920183225624c and db85ef12344d8959eb46eaf522f8cd53372cfc6d
