### ISSUE TITLE
save function hangs with meshing

### ISSUE THREAD

**Issue by bpablo** [phoebe-project/phoebe2#248]
Bundle fails to save when mesh datasets are added.  The program ends up hanging and never finishes. 

Note: It will save the bundle with a mesh attached before run compute, but not after.

**Comment by kecnry** [comment]
Saving meshes do seem to work (at least for me):

```
import phoebe
b = phoebe.default_binary()
b.add_dataset('lc', times=[0])
b.run_compute(pbmesh=True)
b.save('test.phoebe')
```

but if you have meshes at many times then it can take a long time (and perhaps hang if you run out of memory).  

I'm not sure the best way to fix this, but here are some options I can think of:
* exclude meshes while saving by default
* allow for sending a filter to exclude: b.save(exclude={'kind': 'mesh'})
* somehow estimate the resulting memory footprint and raise a warning if too large
* look into alternate formats to fallback on when json becomes too large

**Comment by kecnry** [comment]
Also note that this issue may be alleviated significantly if/when we rewrite the meshing framework (somewhat related to #226) to lower the number of default columns in the returned mesh.

**Comment by kecnry** [comment]
The commit referenced above --- using b.save(compact=True) with ujson installed --- along with the work in the select_mesh_columns --- lowering the number of default columns in the model mesh --- results in building and saving 10 meshes in 7 seconds (as opposed to 1 min before), 100 meshes in 18 seconds (as opposed to over 10 minutes before), and 500 meshes in 1:53 (probably impossible before).

1000 does still fail with a memory error.  If we want to support saving bundles this large, we'll likely need to fallback on a binary format.

**Comment by horvatm** [comment]
What is stored?

Libphoebe essentially gives mesh in Face-vertex format. This is only Fx3 integers and Vx3 floats  per body, where F approx 2V.

**Comment by kecnry** [comment]
@horvatm - we now store two copies (roche and plane-of-sky) Fx3x3 per-body.  This is perhaps a bit larger but more convenient for the user and for plotting.  Storing the same format we do under-the-hood could save us a bit of space, but I don't think it will make a significant difference.  We're still always going to eventually hit the memory limit when serializing to json.

**Comment by horvatm** [comment]
@kecnry If there is a memory limit in json we will eventually hit it and this will be an unpleasant experience. 

 I would nevertheless suggest that internally mesh is stored in lihphoebe native form and we get all properties out of bundle by simple calculations. Even transforming roche mesh into the plane of sky coordinates system can be generated on the fly using (9mul + 6adds)xV floating operations. This up to 10^6 this should take less than 1s of time is we use np.dot(). I guess this takes some restructuring of the code.

Another way to save stuff directly to the disk during the calculations. So before the running calculation we open a file-stream in which data is collected during the calculation. In this way only disk will suffer when we use large meshes or do long simulations.

**Comment by kecnry** [comment]
now that the new meshing framework (with option to select columns) is merged into development, this is as fixed as it can be.  Eventually, with enough meshes or columns exposed, you'll still eventually reach a memory issue.  But unless/until we decide to support an alternate binary format, that is just going to have to be the limit.
