### ISSUE TITLE
list_online_passbands returns empty list

### ISSUE THREAD

**Issue by Raindogjones** [phoebe-project/phoebe2#257]
list_online_passbands returns an empty list and download_passband() fails returning a string of tracebacks ending in the error 

ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version

Issue seems to be caused by the native openssl of Mac OS X not being sufficiently recent to deal with the url redirect on github.  Problem was solved by updating openssl and forcing python to use that version (with brew this is relatively straightforward just running "brew install openssl" followed by "brew install python@2").

**Comment by kecnry** [comment]
added a FAQ entry to the website in https://github.com/phoebe-project/phoebe-project.org/commit/1afdf7e594abd690519997b9efc19a4138d445d8

See [phoebe-project.org/help/faq](http://phoebe-project.org/help/faq).

I'm closing this for now and we can reopen if it becomes a common problem that requires a solution within PHOEBE.
