### ISSUE TITLE
Allow ramping across model atmospheres

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#266]
The computation will currently fail if any surface element has any atmospheric parameter (Teff, logg, abun) outside the tabulated range. It would be convenient to add an explicit ramping option where model atmospheres make a smooth transition to blackbody atmospheres. This option should be off by default and explicitly requested at run_compute() time.

**Comment by kecnry** [comment]
This is under development under the `feature-blending` branch.
