### ISSUE TITLE
Constraining passband luminosity across passbands

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#267]
It would be convenient if colors of the data-sets could be preserved. This can be achieved by introducing pblum_ref, a parameter that points to the reference value for pblum and uses that value to compute the constrained pblums. The current workaround is to access mesh columns directly, i.e.:

lum = np.array([np.sum( self.b['value@abs_normal_intensities@primary@%s' % x]*self.b['areas@primary'].get_value(unit=u.m**2)*self.b['value@ldint@primary@%s' % x])*self.b['value@ptfarea@primary@%s' % x]*np.pi for x in ['u', 'g', 'r', 'i', 'z', 'y']])
        for pbi, pb in enumerate(['u', 'g', 'r', 'i', 'z', 'y']):
            self.b['value@fluxes@model@%s' % pb] *= lum[pbi]/lum[1]

but this is not really user-friendly by any stretch of imagination. This should be supported under the hood.

**Comment by kecnry** [comment]
closed in #331
