### ISSUE TITLE
run_compute() ignores(?) compute methods

### ISSUE THREAD

**Issue by gecheline** [phoebe-project/phoebe2#271]
Passing compute methods within run_compute() doesn't do anything. Default bundle methods used instead.

**Comment by kecnry** [comment]
@gecheline - do you happen to remember which kwargs were being ignored?  There's a chance this has been fixed already... I just tested with distortion_method sent to run_compute and that seems to be respected.

**Comment by gecheline** [comment]
I think it was stuff like ntriangles(?), irrad_method and such. I'll test a bit more now and report back here.

**Comment by gecheline** [comment]
Ok, seems to be working now with passing ntriangles.

**Comment by kecnry** [comment]
Ok, thanks, then I'll close this issue and if anyone runs into anything that isn't respected by run_compute, we can reopen.
