### ISSUE TITLE
ld_func exists for stars and envelope in contact binary

### ISSUE THREAD

**Issue by gecheline** [phoebe-project/phoebe2#283]
Needs to be visible only for the envelope.

**Comment by gecheline** [comment]
Actually, it's all parameters that are added from datasets that are not component (lc, rv, compute..).

**Comment by kecnry** [comment]
ld_func is now in the individual stars instead of in the envelope. However, this problem still exists for compute options (like ntriangles, mesh_method, distortion_method)
