### ISSUE TITLE
Error when attempting to install phoebe

### ISSUE THREAD

**Issue by sscosmos** [phoebe-project/phoebe2#311]
Hi everyone,

I was wondering anyone has encountered the below error when attempting to install on macOS 10.12.6, python 3.6.7. I am assuming it is because phoebe works with python2.x?

Any advice would be much appreciated.

`Collecting phoebe==2.1.2
  Using cached https://files.pythonhosted.org/packages/56/35/58760be61067608fe2eb25d8f460e1f9a710218858694cf17ae2eaefb174/phoebe-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4z/100b17kx6yg9dgxt5ht1pl9m0000gn/T/pip-install-xq2dyi74/phoebe/setup.py", line 6
        print "Numpy is needed for running and building of PHOEBE"
                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Numpy is needed for running and building of PHOEBE")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4z/100b17kx6yg9dgxt5ht1pl9m0000gn/T/pip-install-xq2dyi74/phoebe/`

**Comment by aprsa** [comment]
Hi,

Yep, phoebe doesn't work on python 3 yet; we're actively working on it. Stay tuned.

Cheers,
Andrej

**Comment by sscosmos** [comment]
Thanks for confirming Andrej. Very much appreciated.

**Comment by kecnry** [comment]
Yes, Python 3 support will hopefully be coming in the next release.  See #42 for more details.

If you get a similar message in Python 2, then you need to install numpy before phoebe, as we use numpy distutils to do the setup.

I'll close this for now - let us know if you run into any other issues!
