### ISSUE TITLE
 TypeError: roche_misaligned_Omega_at_vol

### ISSUE THREAD

**Issue by nevilshah235** [phoebe-project/phoebe2#315]
I am working on modelling a semi-detached eclipsing binary H-band light curve and am getting the following error TypeError: roche_misaligned_Omega_at_vol::The volume is beyond critical. I could not find any reference or mention of this error online. I have provided the following parameters - mass of primary and secondary, inclination, radius of primary, and pass band filter information.

**Comment by kecnry** [comment]
This is actually a duplicate of #314. We should have a bugfix release out early next week. Thanks!

**Comment by kecnry** [comment]
This has now been fixed in the 2.1.3 bugfix release.
