### ISSUE TITLE
Transitioning between detached, semidetached, and contact binary cases?

### ISSUE THREAD

**Issue by abhimat** [phoebe-project/phoebe2#317]
I’m currently using phoebe to model a binary system that we expect is a near-contact or contact system.

Is there a recommended way to transition a binary system between the detached, semidetached, or contact systems? Currently with my understanding of phoebe, setting up a system in one of these particular cases leads to an error being thrown when the primary star doesn’t pass the detached or contact case, instead of transitioning to the other case.

Thank you

**Comment by kecnry** [comment]
Unfortunately you're right, this isn't currently possible and will always raise an error. Do you mean transitioning in time within a single run (an eccentric system, for example), or within some sort of fitting procedure? 

The latter can be done manually by checking if you're overflowing and adjusting the hierarchy as necessary to include or exclude the envelope.

**Comment by abhimat** [comment]
Ok thank you. This is part of a fitting procedure, and I will manually check overflowing to decide which setup to use.

I’m running Phoebe under an MCMC sampler (using emcee); are there recommendations on setting up  phoebe to work with MCMC samplers?

**Comment by abhimat** [comment]
Thank you, these are helpful resources! Will follow up if I have feedback
