### ISSUE TITLE
protomesh is empty when running legacy backend with no datasets

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#32]
reproduce:

`import phoebe`
`b = phoebe.Bundle.default_binary()`
`b.add_compute('legacy')`
`b.run_compute(store_mesh=True)`
`b.plot(show=True)`

expected behavior:
since store_mesh=True, the protomesh should still be created and populated (and therefore plotted)

**Comment by bpablo** [comment]
added.
