### ISSUE TITLE
legacy wrapper doesn't set value for third light in bundle

### ISSUE THREAD

**Issue by gecheline** [phoebe-project/phoebe2#324]
'l3' in bundle is 0.0 after calling phoebe.Bundle.from_legacy on a phoebe file with l3 larger than 0.0

**Comment by bpablo** [comment]
l3 works in the examples I have tried. When I look in the code I see that if you have the units of l3 set to "Total Light" that phoebe 2 throws a warning an sets the value to 0. This is because phoebe 2 can't handle "Total Light". Has this changed?
