### ISSUE TITLE
syntax error in setup.py

### ISSUE THREAD

**Issue by CosmicLettuce** [phoebe-project/phoebe2#326]
Hello!  I'm trying to install phoebe on my system using this command:

pip3 install numpy phoebe

and I get the following error:

Requirement already satisfied: numpy in /usr/local/lib64/python3.7/site-packages (1.16.2)
Collecting phoebe
  Using cached https://files.pythonhosted.org/packages/34/74/cc0d9a9e4ba3e5c964be93a8f1b03b1a1f7fe89b981a6e0f86cd94b1052f/phoebe-2.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o4ip6964/phoebe/setup.py", line 6
        print "Numpy is needed for running and building of PHOEBE"
                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Numpy is needed for running and building of PHOEBE")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-o4ip6964/phoebe/

Help!!!

Regards,
Matt

**Comment by kecnry** [comment]
Phoebe 2.1 does not support python 3 (although 2.2 will once released), which should be what's causing this error. Can you try installing with a version of pip that points to a python 2 installation?

**Comment by CosmicLettuce** [comment]
Thanks!  Your suggestion worked!
