### ISSUE TITLE
Observed fluxes generated don’t seem correct

### ISSUE THREAD

**Issue by abhimat** [phoebe-project/phoebe2#349]
When generating observed fluxes with Phoebe, the units do not seem to be correct in the output. Is there something I'm missing in the output units of the flux?

For example, generating the flux for a single star model, with solar parameters at 10 parsecs:

```
sing_star = phoebe.default_star()

sing_star.add_dataset(phoebe.dataset.lc, times=[0], dataset='mod_lc_V', passband='Johnson:V')
sing_star.add_compute('phoebe', compute='detailed', distortion_method='sphere', irrad_method='none')

sing_star.set_value('distance', 10. * u.pc)

sing_star.set_value('teff@component', 5778. * u.K)
sing_star.set_value('requiv@component', 1. * u.solRad)

sing_star.run_compute(compute='detailed', model='run')

print(sing_star['fluxes@lc@mod_lc_V@model'])
```

The output I get for the observed flux is [1.04808646e-35] W / m2. However, this observed flux seems to be too low. When converted to magnitudes, I get 66.344 mag at V band. However, for the sun, the absolute magnitude at V band should be about 4.8. Is there something I’m missing in the unit conversion for the observed flux?

**Comment by aprsa** [comment]
The luminosity of the star in phoebe is _not_ determined by the temperature and radius but rather by the scaling value called _passband luminosity_. By default it is set to 4pi, and you would need to change it to something reasonable (i.e. LSun in V passband). Then you should get the right value for the flux (or apparent magnitude). Please let us know if this makes sense and if we can help further.

**Comment by abhimat** [comment]
Thanks for the quick response! I think that mostly makes sense. I’m not sure if I understand the units of the passband luminosity. Are there specific units that this value has to be passed in and is there documentation about the passband luminosity on the phoebe website?

**Comment by aprsa** [comment]
Sure, take a look at:

http://phoebe-project.org/docs/devel/tutorials/pblum
https://nbviewer.jupyter.org/github/phoebe-project/phoebe2-workshop/blob/2019july/Intro_Tutorial_11_pblum_l3_distance.ipynb

Passband luminosities take some getting used to. If the passband is bolometric, then these are true bolometric luminosities in W. If in a certain passband, these are luminosities as seen in that passband, also in W, and always smaller than bolometric.

**Comment by kecnry** [comment]
Just a quick warning that both of those links are for the development (non-released) version of PHOEBE.  You can find the same tutorial for version 2.1 at:

http://phoebe-project.org/docs/2.1/tutorials/pblum

I'll close this for now, but feel free to continue the conversation here or re-open the issue if you run into any problems.

**Comment by abhimat** [comment]
Thanks for all your help on this, I was trying to determine if it’s possible to similarly set passband luminosity for contact envelopes in contact binaries. I was unable to find this in the documentation, is this possible?

**Comment by kecnry** [comment]
Yes, it works the exact same way, but note that you will provide the luminosity of the primary "half" of the contact envelope instead of the entire system.

**Comment by abhimat** [comment]
How is the passband luminosity set for the contact envelope? If I set the passband luminosities of the individual star in a contact system (via something like `b.set_value('pblum@primary@mod_lc_Kp', star1_pblum_Kp)`), it seems that I don't get the correct fluxes in the final contact binary light curve

I was trying a similar method for the contact envelope (with something like `b.set_value('pblum@contact_envelope@mod_lc_Kp', star1_pblum_Kp)`) but I wasn't able to find a similar pblum property for the contact envelope.

**Comment by kecnry** [comment]
Can you send a minimal example that shows what you're seeing and what you would you expect instead?

You're correct that you need to set `pblum@primary` instead of `pblum@contact_envelope` (which does not exist - that's what I meant in my previous message).  Just as in detached systems, the luminosity of the secondary "half" of the envelope should scale accordingly (unless there is a bug, of course).  Here's a quick example:

```
import phoebe
import numpy as np

b = phoebe.default_binary(contact_binary=True)
b.add_dataset('lc', times=phoebe.linspace(0,0.5,101))

b.set_value('pblum', component='primary', value=2*np.pi)

b.run_compute()
b.plot(show=True)
```

Since these are two identical stars, we'd expect both to contribute approximately 0.5 in flux (ignoring distortion).  As this is a contact, distortion can have a significant impact, but it seems that the luminosity is still scaling correctly (compare to the default pblum of 4 pi where the flux levels are doubled):

![Figure_1-1](https://user-images.githubusercontent.com/877591/63169232-3f8b3280-c004-11e9-9c0a-31a15d441eb7.png)

**Comment by abhimat** [comment]
Thanks for the example, I was able to figure out the bug in my code causing my issues in the contact after following through with your example. Thank you for all your help on this!
