### ISSUE TITLE
Python 2 vs 3 compatibility in libphoebe

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#355]
There are 18 instances of PyString_Type() checks in libphoebe; these will not work in python 3 because of the strings vs. bytes/unicode change in python 3. @kecnry, you pass bytes to other libphoebe functions so perhaps that should be imposed across the board? What do you think @horvatm?

**Comment by horvatm** [comment]
I am using  

#define PyString_Type PyBytes_Type 

to "map" strings to bytes for python 3. libphoebe does not accept strings. 
It only takes bytes.

**Comment by aprsa** [comment]
@horvatm, wd_readdata() fails the PyArg_ParseTupleAndKeywords() call in python 3. That's what prompted me to look closer. Would you like me to post a minimal example?

**Comment by horvatm** [comment]
Does this help:

self.wd_data = libphoebe.wd_readdata(bytes(plfile), bytes(atmfile))

**Comment by aprsa** [comment]
I actually import _bytes from phoebe.utils and use _bytes(string), and it does work, but it made me wonder if we had other instances where this issue breaks python 3 functionality.

**Comment by kecnry** [comment]
libphoebe is not supposed to be exposed to the user... so if _bytes(string) works, then I think that's a suitable solution (and shouldn't be too expensive, although we are repeatedly casting).  My point is, I wouldn't consider having to pass byte strings as breaking python 3 support, we just need to make sure that we do cast whenever necessary.

**Comment by aprsa** [comment]
My question is whether we pass bare strings to libphoebe anywhere else because there are 18 instances in libphoebe that expect strings.

**Comment by horvatm** [comment]
No instance (function) in libphoebe permits strings only bytes This was a verbal agreement. 
I can write a large disclaimer/comment in  libphoebe, for people who read libphoebe.
