### ISSUE TITLE
GCC/G++ version detection in setup.py

### ISSUE THREAD

**Issue by chriswier** [phoebe-project/phoebe2#364]
For Phoebe2 to build correctly, GCC version 5.0 or later needs to be detected in the setup.py file.  

GCC detection roughly does the following steps to get the version (if gcc/g++ exists):
1.  The output from 'gcc --version' or 'g++ --version' is captured into the s variable
2.  The s variable (output) is regex checked for gcc/g++ to show up in the captured string.
3.  The version number is extracted through the find_version_gcc function(s)
4.  find_version_gcc(s) splits the line and returns item at index -2, returned as ver
5.  Python compares LooseVersion(ver) >= LooseVersion("5.0")

The problem here is that the output from "gcc --version" does not follow consistent output patterns, so relying on always returning the split at index -2 does not work reliably with different operating systems.

For example,

Ubuntu 16.04 'gcc --version' returns:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
--> find_version_gcc(s) returns 5.4.0 which is OK

Ubuntu 18.04 'gcc --version' returns:
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
--> find_version_gcc(s) returns 7.4.0-1ubuntu1~18.04.1 which is OK - LooseVersion takes care of it

Centos 7 devtoolset-7 'gcc --version' returns:
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
--> find_version_gcc(s) returns 'Hat' which causes type comparison issues with LooseVersion (str and int)

Centos 7 devtoolset-8 'gcc --version' returns:
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
--> find_version_gcc(s) returns 'Hat' which causes type comparison issues with LooseVersion (str and int)

Note that all these outputs put the GCC version number as a stand-alone items in the output line - ex: 5.4.0 , 7.3.1 , etc.  The find_version_gcc function should be looking for this numeric-only version number and returning it only back.  According to https://gcc.gnu.org/develop.html , GCC version numbers should be formatted as MAJOR.MINOR[.PATCH] where [.PATCH] is optional, giving us some releases with just MAJOR.MINOR and some with patch levels, MAJOR.MINOR.PATCH.

Utilizing this, the output from 'gcc --version' can be parsed using regex to correctly find the GCC version number.

Old function:
```
def find_gcc_version(s):
  if len(s):
   return s.split()[-2]
  else:
    return ''
```

Proposed new function:
```
def find_gcc_versions(s):
  if len(s):
    for i in s.split():
      if re.search("^\d+\.\d+\.*\d*$",i): return i
  return ''
```

The proposed version splits the line, and use regex on each split item against the above GCC version pattern.  If it finds one, it will return back.  If no correctly formatted stand-alone version numbers are found in the string (or if the len(s) is 0), it fails the same way by returning a blank string.

I've tested this proposed patch on Ubuntu 18.04 and Centos 7 (with both devtoolset-7 and devtoolset-8) and it correctly identifies the compiler version now.  Attached is the full patch file.

[0001-use-regex-to-grab-GCC-numeric-version-avoiding-OS-di.patch.txt](https://github.com/phoebe-project/phoebe2/files/4060153/0001-use-regex-to-grab-GCC-numeric-version-avoiding-OS-di.patch.txt)

**Comment by kecnry** [comment]
Thanks for the thorough explanation and patch.  I've applied your patch and will work on releasing a bugfix release soon.
