### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Bhavesh012** [phoebe-project/phoebe2#375]
## Feature Request

It will be a lot of help to have a progress bar for functions such as `run_compute` or `run_solver` to check how much of the progress has taken place.

**Comment by kecnry** [comment]
This has been on the low-priority wish list for quite a while, so I figured I might as well just get around to it now that someone actually asked!

It sounds like you're already using the unreleased "fitting" branch.  I just pushed an update which implements a progressbar for `run_compute` and optimizers in `run_solver` (you will need `tqdm` installed which is not a hard dependency - if you don't have it, you won't see anything).  

Note that the optimizers set the progress based on the number of iterations compared to `maxiters`... so there is a good chance your optimization may complete before reaching 100%.  As for samplers: emcee (also requires `tqdm`) and dynesty already have their own progress bars.  And as for estimators: I don't think it really makes sense to implement at the moment, but can consider that down the road if any become computationally expensive or iterative.

Let me know if everything works for you or if you run into any problems.

**Comment by Bhavesh012** [comment]
Woah, Nice. Thank you.

Yes, I've been trying the unreleased version quite a lot for my summer project and it's simply awesome.

Also, do I need to pass `**kwarg` to see the progress bar (like `progress = True`) in `run_compute` or will it appear automatically?

**Comment by kecnry** [comment]
No need for any arguments - it should detect if tqdm is installed and show the progress bar if it is.  

Also since you're using the unreleased version - just a heads up that we're trying to track down a potential bug in MCMC before release that seems to give biased results.  So just be extra-skeptical and check any results in the meantime.
