### ISSUE TITLE
default compute options by from_legacy

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#4]
Currently adds compute=detailed (phoebe2) and compute=backend (legacy) which isn't very intuitive.  What behavior do we want here?

Reproduce:
`import phoebe`
`b=phoebe.Bundle.from_legacy('default.phoebe')`
`print b['compute']`

**Comment by kecnry** [comment]
Proposal:

compute='phoebe1' with defaults matching the phoebe file
compute='phoebe2' with defaults that are analogous to legacy's as much as possible

This may just be as simple as renaming the tags from detailed->phoebe2 and backend->phoebe1

**Comment by aprsa** [comment]
I am not a big fan of compute='phoebe2' for legacy; why not use compute='legacy' instead?

**Comment by aprsa** [comment]
How about:

compute='p1backend' (run phoebe1 backend with options directly matching those in the file)
compute='legacy' (runs phoebe2 backend with options similar to those in the file)

?

**Comment by kecnry** [comment]
Decision (see #71):

allow the default names to be set by not overriding, resulting in 'phoebe01' and 'legacy01'.

@bpablo - sorry to make you do this again.

**Comment by bpablo** [comment]
I actually dislike using the word legacy. all of the backend commands are pass_to_legacy or compute_legacy or compute parameter set type legacy. And now we want to label the compute parameter set that computes using phoebe2 'legacy'? I strongly dislike this.

**Comment by kecnry** [comment]
No, I am suggesting using the default names for each backend.  The backends will remain named 'phoebe' (the default phoebe2 backend) and 'legacy' (the phoebe1 wrapper).  Whenever you attach new parameters without explicitly stating a label, one will automatically be created by using that method (soon to be 'kind') and a counter.  So the options to run phoebe2 will be 'phoebe01' (not to be confused with phoebe 1.0) and the options to run the legacy wrapper will be 'legacy01'.

Make sense?

**Comment by bpablo** [comment]
changes maded
