### ISSUE TITLE
test on macs

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#41]

**Comment by kecnry** [comment]
phoebe2 should now install on macs as of commits https://github.com/phoebe-project/phoebe2/commit/f3d5c286ee5e68ea47de08ff5b8706f4daf3b719 and https://github.com/phoebe-project/phoebe2/commit/1b6c996ba291ff762e81afbb3fb280f88e890a4b

**Comment by horvatm** [comment]
What are the requirements for Mac OS ? Python version ? ...

I know that stuff was tested on OS X El Capitan (10.11).
