### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#42]

**Comment by kecnry** [comment]
created a new branch to prepare and test python3 support https://github.com/phoebe-project/phoebe2/tree/python3_support

Currently building PHOEBE fails.

We're going to need to update (manually) all C-code wrappers.  See here: http://python3porting.com/cextensions.html.  @horvatm - can you do this for libphoebe at some point and I'll try to do it for burlishstoer?

**Comment by giammarc** [comment]
Hi Kyle,

I can help you do that for burlishstoer.  I'm assuming since we went 
back to burlishstoer you'll want v-gamma support at some point?  If that 
is the case I can try to do both at the same time.

I'm assuming this is not highest priority?

-Joe

**Comment by kecnry** [comment]
@giammarc - no not a huge priority, it would just be nice to get everything building on python3 so we can include python3 support in tests.  As for vgamma - that definitely isn't urgent - I'm still hoping to eventually ditch burlishtoer altogether, but we need it for testing against other methods for now.  We should be able to do that testing without vgamma, and if we decide to keep burlishtoer we can deal with fixing the bugs and including vgamma.

**Comment by kecnry** [comment]
current status: we're running into issues with how python3 handles relative imports differently than python2.  I'll look into the best way to handle inter-package imports in a way that should work for both python2 and 3 and then we can continue to see how the nosetests manage.

**Comment by horvatm** [comment]
Python 3 additionally says that this exception cases have invalid syntax:

constraints/expression.py:        except ValueError, msg:
frontend/io.py:                except ValueError, msg:
parameters/parameters.py:        except ValueError, msg:

**Comment by horvatm** [comment]
After commit fc0503b there are still issues with python 3: 

  File "/home/horvat/.local/lib/python3.5/site-packages/phoebe/parameters/constraint.py", line 529, in freq
    rhs = 2 * np.pi / period
TypeError: unsupported operand type(s) for /: 'float' and 'FloatParameter'

It seem that the logic behind algebraic operations between parameters needs fixing.

**Comment by kecnry** [comment]
The above linked commit fixes many issues, including the constraint issues with division (python3 uses \_\_truediv\_\_ and \_\_rtruediv\_\_ instead of \_\_div\_\_ and \_\_rdiv\_\_).  As noted in the commit message, the marshaled passband files are incompatible with Python 3... I will work on trying to find a solution, but if there all else fails, we may need to host two versions of every pasband file: one built with python2 and one with python3.

**Comment by horvatm** [comment]
Could it just be that the keys in dicts are bytes.
Can you give a short script that uses passbands, so that we can help you find a solution.

**Comment by kecnry** [comment]
f5b83c9d82972c742b110c7e4b1a7c47c67f521f adds support for python3 passband files (which are now pickled instead of marshaled, with the marshaled files used for python2 installations of PHOEBE).
b458fc2ca70d3c30ac0aca1af0d83b6e0d84d883 fixes compiler issues with ceclipse.cpp by removing optimization.

As of now, phoebe runs successfully with irradiation disabled, but enabling irradiation fails with the error: `TypeError: mesh_radiosity_problem_nbody_convex::Problem reading arguments`.

All changes above are merged into development, with the python3_support branch handling testing on Travis until we fix all remaining issues and all science-tests can pass.

d2f1be1fee93e210b7db8b1f699ae7be748a41fe updates Travis to run on Python 3.5 (earliest supported version of Python 3 by astropy) and 3.7 (latest minor release).  Note that travis fails to recognize the version of gcc on travis - we'll need to make the setup script more flexible when the version name isn't in the command name (gcc vs gcc-5 - see https://travis-ci.org/phoebe-project/phoebe2/jobs/484556769).

**Comment by kecnry** [comment]
irradiation issue fixed in 1e487a797ae95b24719fe3e991ae2cfb8a458653 and 02c8584d4e95e90880ee853e4c80279376c5363b.
travis compiler issue fixed in 0af26900650717e52e32e851de2d64d1da874ebc.

Other python3 compatibility fixes in 63441852d3327ac18b67598089609b3efdc00838, 1c657cebb9bd64c33897f67fccfb650c1e90e282

Next problem:  phoebe1's phoebe_legacy branch fails to build in python3.

**Comment by kecnry** [comment]
phoebe1's phoebe_legacy branch now builds on python3, but travis is stalling during the mpi tests for python3 only (cannot easily reproduce locally).
