### ISSUE TITLE
Mac build fails

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#425]
Recent updates to Mac have resulted in PHOEBE no longer compiling correctly.  Mac users with this issue - please post your logs, OS, and compiler versions below.

**Comment by kecnry** [comment]
also see #371 for previous (failed) debugging attempts

**Comment by mbadenas** [comment]
> I tried to install phoebe with pip on a new environment with a MacOS Catalina (10.15.7) and didn't succeed. I then tried [this](https://github.com/phoebe-project/phoebe2/issues/371#issuecomment-647824353), and while it first looked much more promising, it also crashed at the end. The error message I get is copied below. I'd appreciate if anyone know show to solve this problem!
> 
> Building wheel for gevent (PEP 517) ... error
> ERROR: Command errored out with exit status 1:
> command: /Users/mba/opt/anaconda3/envs/phoebe36/bin/python /Users/mbadenas/opt/anaconda3/envs/phoebe36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/f8/zkcc5pg95m94c6ysjfnw79yc0000gp/T/tmpxl1uxgvr
> cwd: /private/var/folders/f8/zkcc5pg95m94c6ysjfnw79yc0000gp/T/pip-install-c70rrnnn/gevent_a585ddd43d654e2f9cdf29dadaf8a725
> 
> .....
> 
> _Successfully built phoebe Failed to build gevent ERROR: Could not build wheels for gevent which use PEP 517 and cannot be installed directly_
> 
> Thank you!

UPDATE: Installed a new environment with python 3.7 and it worked!

**Comment by kecnry** [comment]
Great!  I have also updated the [installation instructions for Mac](http://phoebe-project.org/install/latest/mac/auto) with that tip and pointing back to this thread.  I'll leave the issue open for now since I know other people ran into similar issues - if anyone has suggestions for updates to the installation instructions to avoid these hurdles in the future, please let me know!

**Comment by bpablo** [comment]
In order to install phoebe on a mac you must install the Xcode developer tools in order to get proper compilers. Once this is installed pip install should work without issue.

**Comment by gecheline** [comment]
I was able to install Phoebe successfully on a Mac running Catalina, with freshly installed xcode developer tools. Can you try reinstalling your Xcode cli with
`xcode-select --install`
and then just run `pip install phoebe` in your conda env and let me know what happens?

**Comment by cxl4444** [comment]
Hi, there is a problem when I install Phoebe in Mac with apple silicon and Monterey system. I think part of the reason is the clang version. 
The error shows "[Errno 2] No such file or directory: 'x86_64-apple-darwin13.4.0-clang' ". 
but I get the following after entering clang -- version in the terminal.
clang version 13.0.1
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /opt/homebrew/Caskroom/miniforge/base/envs/phoebe/bin

**Comment by kecnry** [comment]
@cxl4444 - how did you install the compiler (are you just using the OS default or installed a specific compiler within conda)?

**Comment by cxl4444** [comment]
> @cxl4444 - how did you install the compiler (are you just using the OS default or installed a specific compiler within conda)?

It seems the OS default complier if the Mac with M1 chip.

**Comment by kecnry** [comment]
Ok, then can you try installing a compatible installer from within your conda environment and see if the installer picks up on that?  Try conda install `clangxx_osx-64` or `conda install clang-12.0.0`, for example.

**Comment by horvatm** [comment]
Thanks for the full error log. The following  errors are outside libphoebe. 

* clang-13: error: the clang compiler does not support '-march=native'
* error: overriding currently unsupported use of floating point exceptions on this target
* /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/numpy/distutils/checks/cpu_asimdfhm.c:13:21: error: initializing 'float32x2_t' (vector of 2 'float32_t' values) with an expression of incompatible type 'int' 
* /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/numpy/distutils/checks/cpu_asimdfhm.c:14:21: error: initializing 'float32x4_t' (vector of 4 'float32_t' values) with an expression of incompatible type 'int'
ret += (int)vgetq_lane_f32(vfmlslq_high_u32(vf, vhp, vhp), 0);

This error
```
In file included from phoebe/lib/utils.h:15:
phoebe/lib/sincos.h:44:30: error: invalid output constraint '=t' in asm
asm volatile("fsincos" : "=t" (*c), "=u" (*s) : "0" (angle));
````
s inside libphoebe and it is strange. If M1 branch is used this error can not occur, as we have a check in setup.py for exactly this situation. I think we should just switch off optimization in general as only low quality compilers will be affected (not gcc).
