### ISSUE TITLE
passband request: update the passbands of ZTF.

### ISSUE THREAD

**Issue by yinjia86** [phoebe-project/phoebe2#544]
ZTF contains a lot of light curves of eclipsing binary, which are helpful to study the parameters of eclipsing binaries. Could you provide the support of ZTF passbands for PHOEBE ? 

The filters (g, r and i) of Palomar/ZTF can be found:
http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=browse&gname=Palomar&gname2=ZTF&asttype=
It may be necessary to note that there is duplication in the wavelength of g band.

**Comment by aprsa** [comment]
I'll do my best to get to this by the end of this week. I agree that ZTF would be a welcome addition.

**Comment by aprsa** [comment]
ZTF passbands have been computed and pushed to the passband server. Please note that, other than basic testing, these passbands are hot off the press, so use an abundance of caution. I will leave this issue open until I hear of any problems or receive a confirmation that everything seems to work as expected.
