### ISSUE TITLE
CK2004 response computation for custom passband does not appear to be working in PHOEBE 2.2 or 2.3

### ISSUE THREAD

**Issue by abhimat** [phoebe-project/phoebe2#551]
I'm attempting to compute the Castelli & Kurucz 2004 response for a custom passband. However, this does not appear to be working in my installations of phoebe 2.2 or 2.3.

The computation step finishes quickly without displaying any progress (i.e. running `pb.compute_ck2004_response()` and `pb.compute_ck2004_intensities()`). Attempting to test the response for a trial temperature afterwards results in an `Atmosphere parameters out of bounds` error.

Is this a known issue, and is there a possible workaround? Thank you!

**Comment by abhimat** [comment]
Thanks, the new tarball has the necessary fits files, and it all appears to run fine now! I think the tarball was the only issue I had with the custom passband tutorial under 2.2 or 2.3.

**Comment by aprsa** [comment]
Excellent! I also revised the tutorial to reflect the changes (abf40c). Thanks for the nudge! :) I will close this issue now but feel free to reopen if you run into any issues.
