### ISSUE TITLE
legacy wrapper disable reflection

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#56]
It would be nice if the legacy wrapper had a switch to disable reflection entirely to test against phoebe2's refl=False.  Under the hood this will probably need to override all albedos and set them to 0.

Perhaps a boolean parameter called refl, with mult_refl then only being relevant if refl=True?

Or a single parameter that is refl_num: 
* if 0, disable reflections by setting alb to 0
* if 1, set reffect_switch=False, reffect_num=1
* if >1, set reffect_switch=True, reffect_num=N

**Comment by bpablo** [comment]
Done.

**Comment by kecnry** [comment]
https://github.com/phoebe-project/phoebe2/commit/21de862a069193280f4f64f912ede469f74f793c
