### ISSUE TITLE
failed to excute phoebe.default_binary() function

### ISSUE THREAD

**Issue by zzxihep** [phoebe-project/phoebe2#563]
When I upgrade the astropy from 4.3.1 to 5.0, then the phoebe.default_binary() will run failure. It seems something wrong about units. When I back the astropy version to 4.3.1, everything will be ok. The failure report is below
`In [2]: b = phoebe.default_binary()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-7b512fd43412> in <module>
----> 1 b = phoebe.default_binary()

~/.local/lib/python3.9/site-packages/phoebe/__init__.py in default_binary(*args, **kwargs)
    494 
    495 def default_binary(*args, **kwargs):
--> 496     return Bundle.default_binary(*args, **kwargs)
    497 
    498 default_binary.__doc__ = Bundle.default_binary.__doc__

~/.local/lib/python3.9/site-packages/phoebe/frontend/bundle.py in default_binary(cls, starA, starB, orbit, semidetached, contact_binary, force_build)
   1084                 b = cls.open(os.path.join(_bundle_cache_dir, 'default_contact_binary.bundle'))
   1085             else:
-> 1086                 b = cls.open(os.path.join(_bundle_cache_dir, 'default_binary.bundle'))
   1087 
   1088             secondary = 'secondary'

~/.local/lib/python3.9/site-packages/phoebe/frontend/bundle.py in open(cls, filename, import_from_older, import_from_newer)
    884             b.set_hierarchy()
    885 
--> 886         b.run_all_constraints()
    887         return b
    888 

~/.local/lib/python3.9/site-packages/phoebe/frontend/bundle.py in run_all_constraints(self)
   7166         for constraint_id in [p.uniqueid for p in self.filter(context='constraint', **_skip_filter_checks).to_list()]:
   7167             previous_value = self.get_parameter(uniqueid=constraint_id, **_skip_filter_checks).constrained_parameter.value
-> 7168             param = self.run_constraint(uniqueid=constraint_id, return_parameter=True, skip_kwargs_checks=True, suppress_error=False)
   7169             if param not in changes and not _is_equiv_array_or_float(param.value, previous_value):
   7170                 changes.append(param)

~/.local/lib/python3.9/site-packages/phoebe/frontend/bundle.py in run_constraint(self, twig, return_parameter, suppress_error, **kwargs)
   7057 
   7058         try:
-> 7059             result = expression_param.get_result(suppress_error=False)
   7060         except Exception as e:
   7061             if expression_param.uniqueid not in self._failed_constraints:

~/.local/lib/python3.9/site-packages/phoebe/parameters/parameters.py in get_result(self, t, use_distribution, suppress_error, distribution_uniqueids)
  11693                 # values = get_values(vars, safe_label=True)
  11694 
> 11695                 values = get_values(self._vars+self._addl_vars, safe_label=True)
  11696 
  11697 

~/.local/lib/python3.9/site-packages/phoebe/parameters/parameters.py in get_values(vars, safe_label, string_safe_arrays, use_distribution, needs_builtin)
  11587                     return _single_value(var.get_quantity(), string_safe_arrays)
  11588 
> 11589             return {var.safe_label if safe_label else var.user_label: _value(var, string_safe_arrays, use_distribution, needs_builtin) for var in vars}
  11590 
  11591         eq = self.get_value()

~/.local/lib/python3.9/site-packages/phoebe/parameters/parameters.py in <dictcomp>(.0)
  11587                     return _single_value(var.get_quantity(), string_safe_arrays)
  11588 
> 11589             return {var.safe_label if safe_label else var.user_label: _value(var, string_safe_arrays, use_distribution, needs_builtin) for var in vars}
  11590 
  11591         eq = self.get_value()

~/.local/lib/python3.9/site-packages/phoebe/parameters/parameters.py in _value(var, string_safe_arrays, use_distribution, needs_builtin)
  11585                     return _single_value(var.get_quantity(t=t), string_safe_arrays)
  11586                 else:
> 11587                     return _single_value(var.get_quantity(), string_safe_arrays)
  11588 
  11589             return {var.safe_label if safe_label else var.user_label: _value(var, string_safe_arrays, use_distribution, needs_builtin) for var in vars}

~/.local/lib/python3.9/site-packages/phoebe/parameters/parameters.py in _single_value(quantity, string_safe_arrays)
  11549                 if isinstance(quantity, u.Quantity):
  11550                     if self.in_solar_units:
> 11551                         v = np.float64(u.to_solar(quantity).value)
  11552                     else:
  11553                         v = np.float64(quantity.si.value)

~/.local/lib/python3.9/site-packages/phoebe/dependencies/unitsiau2015/__init__.py in to_solar(object)
    183 
    184     if physical_type not in _physical_types_to_solar.keys():
--> 185         raise NotImplementedError("cannot convert object with physical_type={} to solar units".format(physical_type))
    186 
    187     return object.to(_physical_types_to_solar.get(physical_type))

NotImplementedError: Constraint 'freq@primary@star@constraint' raised the following error while attempting to solve for 'freq@primary@star@component'.  Consider flipping the constraint or changing the value of one of ['period@primary@star@component', 'freq@primary@star@component'] until the constraint succeeds.  Original error: cannot convert object with physical_type=angular frequency/angular speed/angular velocity to solar units`

**Comment by kecnry** [comment]
Thanks for reporting this.  Everyone will need to downgrade astropy until we can get a proper fix out that handles the changes in astropy units.
