### ISSUE TITLE
passband request: super SDSS

### ISSUE THREAD

**Issue by JamesMunday98** [phoebe-project/phoebe2#566]
Hi. I made a request here last week but it seems to be a space that isn't looked at so often - https://github.com/phoebe-project/phoebe2-tables/issues/5      (which is linked to on here http://phoebe-project.org/contribute#features ). Issues I had trying to make them myself are in that request.

The filters themselves are lines 43 to 47, ugriz, at http://www.vikdhillon.staff.shef.ac.uk/ultracam/filters/filters.html

Or the throughputs to the detector for ugriz are:
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.u_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.g_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.r_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.i_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter
http://svo2.cab.inta-csic.es/theory///fps3/index.php?id=GTC/HIPERCAM.z_s&&mode=browse&asttype=astro&gname=GTC&gname2=HIPERCAM#filter

Would someone mind adding the passbands whenever possible (no particular hurry, the repost is just to make sure that the request has been seen). Listed are links to the throughput for each band. I'll use the 5 a lot, so I would prefer to choose the actual passbands over the SDSS primes, where there is a strong enough difference between the transmission functions to make it worthwhile. Cheers

**Comment by aprsa** [comment]
I have seen the request but have been very busy this week. I'll try to get to it early next week.

**Comment by JamesMunday98** [comment]
Appreciated, thank you.

**Comment by JamesMunday98** [comment]
Have you been able to look into this at all yet, @aprsa ?

**Comment by aprsa** [comment]
I'm finally done with the new passband framework -- it's essentially a rewrite that will allow us to extend to new atmospheres and passbands a lot easier. While we're prepping that for an official release, I'll go back and create super-SDSS passbands this week. I'll post here once I'm done. Sorry it's taking this long, rewriting passbands and building blending has taken essentially all of my time.

**Comment by aprsa** [comment]
@JamesMunday98, SSDSS passbands are now implemented. Please note two caviats: (1) while the passbands pass the initial QC, there has been no thorough testing done, so please exercise caution and let me know of any problems; (2) extinction tables have not been included for these passbands for the time being; those are being calculated.

The passbands are named `SSDSS:us`, `SSDSS:gs`, `SSDSS:rs`, `SSDSS:is` and `SSDSS:zs`. If you do:
```
>>> import phoebe
>>> phoebe.list_online_passbands()
```
you should be able to see them. When you use them, they should download automatically.

**Comment by JamesMunday98** [comment]
thank you very much for spending the time to add these Andrej. I see them all on there and will post if there are any issues
