### ISSUE TITLE
support atm=atmcof or remove from parameter options

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#57]
reported by @bpablo 

passbands._log10_Inorm_wd is currently commented out.  If this isn't going to be supported by 2.0b, then we need to remove 'atmcof' as a choice for the 'atm' parameter and then change the value that is set by the legacy importer.

**Comment by aprsa** [comment]
This function has been replaced by extern_* atmosphere module that does the exact same thing. Anything except extern_planckint and extern_atmcof that deals with WD-like atmospheres should be removed.

**Comment by kecnry** [comment]
ok.  Somehow 'atmcof' is in passbands._pbtable.values(), so that needs to be fixed and will then automatically remove it from the list of choices in the parameter.

There's also an `elif atm=='atmcof'` in the passbands module.  Is that safe to remove or should we just swap it out with a NotImplementedError?

**Comment by aprsa** [comment]
Fixed.
