### ISSUE TITLE
celerite warning when running MCMC without GPs on external machine

### ISSUE THREAD

**Issue by ayushmoharana** [phoebe-project/phoebe2#575]
I am running an MCMC solver on an external machine. I get the following output repeated several times:
<frozen importlib._bootstrap>:228: FutureWarning: pybind11-bound class 'celerite.solver.CholeskySolver' is using an old-style placement-new '__setstate__' which has been deprecated. See the upgrade guide in pybind11's docs. This message is only visible when compiled in debug mode.

I am not using any GPs .

**Comment by kecnry** [comment]
This is probably just being called when phoebe attempts to import celerite (which it does whether or not you have GPs to know whether its installed).  Does it cause any issues other than just adding warnings to the logs?

**Comment by ayushmoharana** [comment]
The MCMC process itself doesn't start on time (compared to the notebooks).

**Comment by kecnry** [comment]
Ok, my best advice for now would be to use a custom virtual/conda environment on the external machine (or ask them to remove/upgrade/don't use debug mode when installing celerite).  I'm not sure there is much we can do from the phoebe-side short of deferring/skipping the import, which would be somewhat ugly.  If that doesn't help or isn't an option, let me know and I can help you get setup with a custom installation of phoebe that doesn't import celerite at all.

**Comment by kecnry** [comment]
Closing this for now since I don't think there is much we can do (without moving to a full plugin architecture).  If anyone is still running into this problem and cannot workaround on the server-side, feel free to reopen.
