### ISSUE TITLE
rv_grav units/order of magnitude mismatch

### ISSUE THREAD

**Issue by gecheline** [phoebe-project/phoebe2#608]
A Sun-Jupiter system with rv_grav enabled returns orders of magnitude higher RVs for the Sun than expected (~600 m/s expected, ~700 km/s returned)

A single Sun-like star has the correct rv_grav offset though.

**Comment by aprsa** [comment]
Is there a minimal script available to reproduce this issue?

**Comment by kecnry** [comment]
Fixed by #694
