### ISSUE TITLE
impossible to add dataset with flipped constraints

### ISSUE THREAD

**Issue by bpablo** [phoebe-project/phoebe2#62]
Adding a dataset after changing a constraint causes the following error:

RuntimeError: maximum recursion depth exceeded

`b = phoebe.Bundle.default_binary()`
`b.flip_constraint(solve_for='sma', constraint_func='mass', component='primary')`
`b.add_dataset('LC', time = np.linspace(0,30.0, 10.))'

**Comment by kecnry** [comment]
can't reproduce anymore, I'm going to assume this accidentally got fixed.
