### ISSUE TITLE
How to get data residuals of time series?

### ISSUE THREAD

**Issue by AstroJLin** [phoebe-project/phoebe2#620]
Hi,

Here, I used model to fit the data and get the data residuals. With this code (_ =b.plot(fig=mplfig,kind='lc',dataset='lcB', model='emcee_a103', yunit='', ylabel='NormalizedFlux', y='residuals',label=r'B band', legend=True, s={'dataset': 0.005}, marker={'dataset': 'o'}, show=True)), it seems that only residual data can be drawn, and this residual data cannot be obtained. But I want to do further analysis on the residual of the data, can you tell me how to get this residual data?

The data residuals is as follow:
![data res](https://user-images.githubusercontent.com/86318178/180641582-202cd529-51c0-468c-9fc4-e10689b7e67c.png)

**Comment by kecnry** [comment]
You can access the residuals array by calling [b.calcuate_residuals()](http://phoebe-project.org/docs/latest/api/phoebe.parameters.ParameterSet.calculate_residuals) (which will be in time-order and the same length as the dataset observation times).  If you also need the array of phases, you can pass your dataset times to [b.to_phase](http://phoebe-project.org/docs/latest/api/phoebe.frontend.bundle.Bundle.to_phase).

I'll close this issue, but if you run into any problems, feel free to re-open it or [start a new discussion](https://github.com/phoebe-project/phoebe2/discussions/new).

-Kyle
