### ISSUE TITLE
How do I handle software installation problems

### ISSUE THREAD

**Issue by Yzxastr** [phoebe-project/phoebe2#638]
HI,i ran into this bug when I installed it in anaconda by 'pip install numpy phoebe ' or 'pip3 install numpy phoebe ' . I have installed the latest Visual Studio 2022 and Microsoft Visual C++ Redistributable.
My bug is as follows:
![bug1](https://user-images.githubusercontent.com/102363557/194208646-b44be68b-b6cf-47cc-83a5-4f93402641
![bug2](https://user-images.githubusercontent.com/102363557/194208651-ce2be573-0922-4bac-93d1-335201fd402a.png)
5c.png)

Could you give me some suggestions to solve this bug?

**Comment by Yzxastr** [comment]
![bug1](https://user-images.githubusercontent.com/102363557/194208848-e0e44e4b-5d7f-4616-9328-7c9cac0b0f1b.png)

**Comment by kecnry** [comment]
Sorry you're running into issues!  We don't have too much experience with windows systems ourselves, so would definitely consider support for windows somewhat experimental and are trying to revise the installation instructions based on what works for users.

Just to try to get a few more details on what might be different between what you tried and what has worked for other users:
* Did you also install the "coding pack for python" listed on the [windows install page](http://phoebe-project.org/install/latest/windows/auto)?  
* Are you using a conda environment or trying to install without?

Thanks
Kyle

**Comment by horvatm** [comment]
Did installation of numpy via
`  pip install numpy`
succeed?

Cheers, Martin

**Comment by Yzxastr** [comment]
succeed




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Martin ***@***.***&gt;; 
发送时间: 2022年10月7日(星期五) 晚上10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [phoebe-project/phoebe2] How do I handle software installation problems (Issue #638)





 
Did installation of numpy via
   pip install numpy
 succeed?
 
Cheers, Martin

**Comment by Yzxastr** [comment]
I have installed the "coding pack for python", and i used a conda environment to install phoebe by "pip install numpy phoebe".






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "phoebe-project/phoebe2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [phoebe-project/phoebe2] How do I handle software installation problems (Issue #638)





 
Sorry you're running into issues!  We don't have too much experience with windows systems ourselves, so would definitely consider support for windows somewhat experimental and are trying to revise the installation instructions based on what works for users.
 
Just to try to get a few more details on what might be different between what you tried and what has worked for other users:
  
Did you also install the "coding pack for python" listed on the windows install page?
 
Are you using a conda environment or trying to install without?
  
Thanks
 Kyle

**Comment by horvatm** [comment]
I suggest that you do 
`pip  -v --log phoebe_install.log install numpy phoebe `
And send the full log file.

**Comment by Yzxastr** [comment]
First of all,&nbsp; I would like to thank you very much for your warm-hearted help.&nbsp;I have already installed it.&nbsp;
Then I would like to ask if you have an example of solving the parameters of a Detached binary .
I also wanted to ask phoebe how she solves absolute parameters by combining light and radial velocity curves.



Could you give me a example? Thanks a lot.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "phoebe-project/phoebe2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [phoebe-project/phoebe2] How do I handle software installation problems (Issue #638)





 
Sorry you're running into issues!  We don't have too much experience with windows systems ourselves, so would definitely consider support for windows somewhat experimental and are trying to revise the installation instructions based on what works for users.
 
Just to try to get a few more details on what might be different between what you tried and what has worked for other users:
  
Did you also install the "coding pack for python" listed on the windows install page?
 
Are you using a conda environment or trying to install without?
  
Thanks
 Kyle

**Comment by kecnry** [comment]
Glad to hear you got it working!  If there are any changes to the installation instructions for windows you'd suggest, please let us know.

You can find numerous [tutorials](http://phoebe-project.org/docs/2.4/tutorials) and [examples](http://phoebe-project.org/docs/2.4/examples) on our website.  Please give those a look first and [let us know if you have any questions](https://github.com/phoebe-project/phoebe2/discussions).

I'll close this issue for now since it seems that you were able to get phoebe installed successfully.

**Comment by Yzxastr** [comment]
OK.Thank you so much.



---Original---
From: "Kyle ***@***.***&gt;
Date: Fri, Oct 14, 2022 19:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [phoebe-project/phoebe2] How do I handle software installationproblems (Issue #638)




 
Glad to hear you got it working!  If there are any changes to the installation instructions for windows you'd suggest, please let us know.
 
You can find numerous tutorials and examples on our website.  Please give those a look first and let us know if you have any questions.
 
I'll close this issue for now since it seems that you were able to get phoebe installed successfully.
