### ISSUE TITLE
How do I handle type error problem?

### ISSUE THREAD

**Issue by qintianp** [phoebe-project/phoebe2#639]
Hi, i installed phoebe-2.3.59 or latest phoebe-2.4.5 successfully, but when i enter ' import phoebe ', i ran into bug.
My bug is as follows:
![bug](https://user-images.githubusercontent.com/115246550/194567496-71c6db26-ea90-4a2d-9c91-1a0ce28145f0.png)

**Comment by kecnry** [comment]
Can you show more of the traceback (perhaps copy-pasted as text or attached as a text file)?  I suspect this is coming from loading the passband, but it would be useful to confirm that first.

Thanks!
Kyle

**Comment by qintianp** [comment]
My bug is as follows:

![image](https://user-images.githubusercontent.com/115246550/194682432-f0ace4aa-2170-47e5-a29d-83270039b19d.png)

![image](https://user-images.githubusercontent.com/115246550/194682434-367b1ae7-3dc2-45c3-b5f0-1fe16680c62e.png)

![image](https://user-images.githubusercontent.com/115246550/194682443-8830261c-d83a-49af-9d52-391507987ded.png)

**Comment by kecnry** [comment]
Great, thanks!  Let's first make sure that the passband file isn't corrupted (the first warning suggests maybe the file got truncated when it was being downloaded or saved to your system). Try deleting the file mentioned at the top and rerunning your script, which should force it to redownload the file from the phoebe website.

**Comment by qintianp** [comment]
Hello, do you mean delete the gaia_bp.fits? I tried, but I still got same error.

**Comment by qintianp** [comment]
Thanks, the problem has been solved.
