### ISSUE TITLE
re-implement missing ld_funcs

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#64]
Removed ld_funcs since alpha that we may want to consider re-implementing:
- hillen
- claret
- uniform

These would need to be implemented in the passbands module, libphoebe, and added as choices in both phoebe.parameters.dataset and phoebe.parameters.component

**Comment by kecnry** [comment]
@aprsa - is it worth implementing any of these at some point or is this issue safe to close?

**Comment by horvatm** [comment]
I think claret is called power in phoebe 2.0.

**Comment by aprsa** [comment]
This is done, so safe to close.
