### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Yzxastr** [phoebe-project/phoebe2#643]
I have phoebe installed in anaconda on windows ,  but, it indicates that a connection to the server cannot be established when i 'import phoebe' in jupyter.

**Comment by kecnry** [comment]
What is the exact message and is it a warning or an error (did it actually prevent the import or just print a message)?  

If it isn't referring to the jupyter kernel as @aprsa mentioned, then it might be referring to the passband server.  If that's the case, it should only be a warning and will only prevent you from automatically fetching passbands that are available online but not preinstalled with phoebe.  You can either debug that connection issue (sometimes either a firewall or SSL problem) or download and install the passband files manually from http://phoebe-project.org/tables/pbs

**Comment by Yzxastr** [comment]
I have import phoebe successfully in jupyter.Thanks a lot.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "phoebe-project/phoebe2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 晚上10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [phoebe-project/phoebe2] import error (Issue #643)





 
What is the exact message and is it a warning or an error (did it actually prevent the import or just print a message)?
 
If it isn't referring to the jupyter kernel as @aprsa mentioned, then it might be referring to the passband server.  If that's the case, it should only be a warning and will only prevent you from automatically fetching passbands that are available online but not preinstalled with phoebe.  You can either debug that connection issue (sometimes either a firewall or SSL problem) or download and install the passband files manually from http://phoebe-project.org/tables/pbs

**Comment by aprsa** [comment]
I'm glad to hear that your issue was resolved. That said, it would be useful to know what the problem was and what you did to solve it -- so that others who come across this thread know what the actual issue was.

**Comment by Yzxastr** [comment]
I use the same kernel as in anaconda and&nbsp;download&nbsp;the passband files manually from&nbsp;http://phoebe-project.org/tables/pbs,then,it 's be able to import sucessfully in jupyter.Thanks again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "phoebe-project/phoebe2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月16日(星期天) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [phoebe-project/phoebe2] import error (Issue #643)





 
I'm glad to hear that your issue was resolved. That said, it would be useful to know what the problem was and what you did to solve it -- so that others who come across this thread know what the actual issue was.
