### ISSUE TITLE
Why can't I get a good fit when I use a Gaussian process

### ISSUE THREAD

**Issue by Yzxastr** [phoebe-project/phoebe2#645]
This is my original drawing
![QQ截图20221024232953](https://user-images.githubusercontent.com/102363557/197567392-cb30170f-cbc4-425a-a82c-2cfce8d7504e.png)
This is GPfit
![QQ截图20221024233136](https://user-images.githubusercontent.com/102363557/197567554-32db88a9-4c82-459c-8a44-24f25c8e644c.png)
This is my code
![QQ截图20221024233331](https://user-images.githubusercontent.com/102363557/197567644-d5b96086-78ea-4397-a7c9-955a82d626d2.png)

**Comment by kecnry** [comment]
This looks like a flux-scaling issue to me, you likely need to set/fit `pblum` to an appropriate value (see the [pblum tutorial](http://phoebe-project.org/docs/latest/tutorials/pblum) for more details).  I'd also suggest trying to make sure that you have a decent synthetic light curve that agrees with your observations _before_ adding GPs into the mix.

**Comment by Yzxastr** [comment]
Thank you so much,i have get good fit  by set/fit pblum to an appropriate value.
