### ISSUE TITLE
finite integration time

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#65]
Pretty self-explanatory: implement the ability for the model to average over a provided exposure time per-datapoint.

This will likely be computationally expensive and will require some infrastructure work to implement.

**Comment by aprsa** [comment]
This can be done in two ways: by oversampling or by convolution. I actually think convolution would be better, and it would definitely be far more efficient.

**Comment by kecnry** [comment]
I currently listed this under 2.0 - is this something we need to discuss and include for 2.0b or can we postpone it?

**Comment by kecnry** [comment]
Plan:
* implement per-dataset finite integration for LCs for 2.0b (split into new issue: #68)
* defer per-timepoint exposure times
* defer finite integration for other dataset types
