### ISSUE TITLE
line profile bug

### ISSUE THREAD

**Issue by chipkob** [phoebe-project/phoebe2#668]
I'm reporting a bug in the generation of line profiles. I'm following the simple example tutorial at   http://phoebe-project.org/docs/2.4/tutorials/LP

>>> import phoebe
>>> phoebe.__version__
'2.4.5'
>>> b = phoebe.default_binary()
>>> b.add_dataset('lp', times=[0,1,2], wavelengths=phoebe.linspace(549, 551, 101))
<ParameterSet: 100 parameters | contexts: compute, dataset, figure, constraint>
>>> b.run_compute(irrad_method='none')
<ParameterSet: 5 parameters | qualifiers: comments, flux_densities, wavelengths>
>>> print(b.filter(qualifier='flux_densities', context='model'))
ParameterSet: 3 parameters
R  00.000000@flux_densities@la...: [1. 1. 1. ... 1. 1. 1.] W / (m2 nm)
R  01.000000@flux_densities@la...: [nan nan nan ... nan nan nan] W / (m2 nm)
R  02.000000@flux_densities@la...: [nan nan nan ... nan nan nan] W / (m2 nm)

See that the latter two time entries return nan whereas the example output on the tutorial page shows 1. 1. 1.  
Something seems amiss.  This error also happens in phoebe 2.4.2.    phoebe 2.2.2 appears to function properly in this regard, however.

**Comment by kecnry** [comment]
Thanks for the report.  Although it isn't exactly the same, it is likely that #637 will fix this.  Feel free to try that branch and see if it works for you, or we will just try to double check this case before releasing that.

**Comment by aprsa** [comment]
I can confirm that #637 fixes this.

**Comment by kecnry** [comment]
#637 fixes this and is included in the 2.4.7 release.

**Comment by chipkob** [comment]
Hmm, I still get nans for all line profiles after the first.  My terminal transcript follows.  There must be something else involved...
Chip 


Successfully installed phoebe-2.4.7
(base) bash-4.4$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import phoebe
>>> b = phoebe.default_binary()
>>> b.add_dataset('lp', times=[0,1,2], wavelengths=phoebe.linspace(549, 551, 101))
<ParameterSet: 100 parameters | contexts: compute, figure, constraint, dataset>
>>> b.run_compute(irrad_method='none')
100%|████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 17.26it/s]
<ParameterSet: 5 parameters | qualifiers: comments, wavelengths, flux_densities>
>>> print(b.filter(qualifier='flux_densities', context='model'))
ParameterSet: 3 parameters
R  00.000000@flux_densities@la...: [1. 1. 1. ... 1. 1. 1.] W / (m2 nm)
R  01.000000@flux_densities@la...: [nan nan nan ... nan nan nan] W / (m2 nm)
R  02.000000@flux_densities@la...: [nan nan nan ... nan nan nan] W / (m2 nm)
>>> phoebe.__version__
'2.4.7'

**Comment by kecnry** [comment]
@chipkob - I cannot reproduce this on my own machine with 2.4.7, but since the interpolation is implemented via numpy, different version of numpy might behave differently.  What version of numpy do you have installed?  Does updating numpy (if you're able/willing) fix the problem?

**Comment by chipkob** [comment]
Ahha!  Upgrade to current numpy version fixed this.  Sorry for the trouble.    My numpy was 1.21.5 and now 1.23.5 works.

**Comment by kecnry** [comment]
Ok, good to know its working for you!  I'll leave the issue open though since we say that we support numpy as old as 1.12 - so we need to either bump that version requirement or tweak the logic to support older versions as well.

**Comment by chipkob** [comment]
In case it helps I'll note that numpy 1.20.1 with phoebe 2.2.2 works just fine.

**Comment by aprsa** [comment]
I'm trying to reproduce this but for me it's still working with numpy 1.21.5; I also tested against 1.22 and the tests are also passing. So there must be something else at play here. @chipkob, any chance you still have the setup handy that produces the nans? If so, could you provide me with all your package versions and architecture?
