### ISSUE TITLE
marching fails to converge before critical potentials are reached

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#70]
This only happens when *very* close to the critical potential - libphoebe.roche_critical_potential reports that we're not overflowing at L1 or L2, but meshing has issues converging.

`import phoebe`
`b=phoebe.Bundle.default_binary()`
`b.set_value('ecc', 0.6795)`
`b.add_dataset('MESH', time=[b.get_value('t0_perpass@component')])`
`b.run_compute()`
`b.plot(show=True)`

results in "Warning: Projection did not converge" and meshes are clearly overlapping.

How close you can safely get to the critical potentials is likely dependent on the value of delta (size of triangles in marching).

**Comment by aprsa** [comment]
This can likely be worked around by starting from the point radius instead. This should work for detached and semi-detached.

**Comment by kecnry** [comment]
Projection warnings were fixed by changing to starting point (as @aprsa suggested, see b5ab746).

We can still, however, get overlapping meshes because the sum of the x-boundary of the primary and secondary *can* exceed the separation of the stars when d<1 or F>1 (because we treat each star separately as the primary component).

Hopeful solution: do an additional system check to make sure this sum at d=1-e never exceeds d=1-e.  @horvatm will write a libphoebe wrapper to access the x-boundaries and then @kecnry will include in the system checks.  These scenarios will then throw warnings through the logger when changing parameter values and will raise errors before running computations.
