### ISSUE TITLE
Not an issue: JKTEBOP backend produces internally consistent light curves for spherical stars

### ISSUE THREAD

**Issue by jsinkbaek** [phoebe-project/phoebe2#703]
Hi again @kecnry and @aprsa,

I did not know whether to put this in "Issues" or "Discussion".
Just wanted to let you know that today, with the help of @Raindogjones, I tested the internal PHOEBE translation of temperatures to surface brightness ratios when using the JKTEBOP backend. The result is that, using manual limb darkening, no reflection, and spherical stars, there is absolutely no difference between:

- Running JKTEBOP internally with the implemented surface brightness ratio approximation
- Running JKTEBOP externally with a surface brightness ratio approximated using:
   `pb=phoebe.get_passband('passband')`
   `surface_brightness_ratio=pb.Inorm(Teff=T1,logg=logg1)[0]/pb.Inorm(Teff=T2,logg=logg2)[0]`

Of course, there should not be any difference either, since the surface brightness approximation assumes spherical stars. But this is just a confirmation that the implementation does what is expected from the PHOEBE side.

The atmosphere models used was ck2004.
The tests have been done for a few different parameters, in the Strömgren u passband, and the Bolometric passband. For the Bolometric passband, I used `surface_brightness_ratio=(T2/T1)^4` for the external case, and the two codes hold up reasonably well still.

I have not tested the spherical pblum approximation for the bi-axial ellipsoid treatment that JKTEBOP can do, since I personally have zero interest in ever using that. But in case you want to, I can send you the notebook I used and a zip file with a self-contained JKTEBOP implementation with Makefile and everything.

Some plots below.

### Bolometric T2=T1=5000, rsum=0.2, rratio=1.0
![fig1](https://user-images.githubusercontent.com/56873820/219070672-19d2bc8b-99d1-4f7e-bf58-0c9c2abc16f3.png)

### Bolometric T2=T1=5000, rsum=0.2, rratio=0.3
![fig2](https://user-images.githubusercontent.com/56873820/219071193-a5e954b2-22c1-43ea-8129-f07682538660.png)

### Bolometric T2=4500, T1=7999, rsum=0.2, rratio=0.3
![fig5](https://user-images.githubusercontent.com/56873820/219071946-daa9cd93-396f-40ab-97ae-01b872beb520.png)
![fig4](https://user-images.githubusercontent.com/56873820/219071983-30b59e8d-75d3-46f0-ae12-d2a4db844e1a.png)

### Strömgren u T2=5000, T1=7500, rsum=0.2, rratio=0.3
![fig6](https://user-images.githubusercontent.com/56873820/219072281-f44f9be2-782f-4ac8-9b55-013a38762a77.png)
![fig7](https://user-images.githubusercontent.com/56873820/219072300-538b8b5c-0a65-42f9-8e8c-e6e4250d1df8.png)

**Comment by kecnry** [comment]
Great, thanks for this report @jsinkbaek!  I think its fine here, but since its not something that needs addressing, I'll mark it as closed and we can still find it or reference it if needed.
