### ISSUE TITLE
volume conservation can result in potential lower than that defined at periastron

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#71]
Reproduce:

`import phoebe; import numpy as np`
`b=phoebe.Bundle.default_binary()`
`b.add_dataset('LC', time=np.linspace(0,3,101))`
`b.set_value('ecc', 0.675)`
`b.run_compute()`

trimmed output:
lobe_x_points::problems with right boundary
roche_area_volume:Determining lobe's boundaries failed
SystemError: error return without exception set

Note: unlike in #70, this configuration will mesh appropriately if forced to mesh at periastron.  It's only after reaching periastron the second time and the instantaneous potential is determined by volume conservation which provides a slightly lower value that this fails.  Since we only do system checks against the critical potential with the defined values, this is never caught and results in a crash.

One possible solution: forbid volume conservation to result in a potential lower than the originally defined value.  But if we go in this direction then we need to be careful to not apply this logic for non-keplerian cases.

**Comment by kecnry** [comment]
I am now getting the following error for the same code-snippet above:

lobe_x_points::left lobe does not seem to exist
omegaL1=10.7511 omegaL2=7.7744
roche_area_volume:Determining lobe's boundaries failed
SystemError: error return without exception set

Is this caused by something else and is a different bug?

**Comment by horvatm** [comment]
What it the code that you are running? Is this test_ecc.py?

**Comment by kecnry** [comment]
No, the one quoted at the top of this issue

**Comment by horvatm** [comment]
For some reason the potential is Omega0=10.7489 at q=1, F=1, delta=0.325. The critical potentials 
omegaL1=10.7511, omegaL2=7.7744 suggest that the left/primary lobe does not exist anymore.

**Comment by kecnry** [comment]
But the defined Omega0 at periastron is 10.8718.  Is volume conservation still taking us below this value for some reason?
