### ISSUE TITLE
Potential computation from volume very slow (2 orders of magnitude slower than WD)

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#73]
The comparison between phoebe2 and WD is attached below for pot1=pot2=8.0, e=0.4.

![diffs](https://cloud.githubusercontent.com/assets/2669162/18299469/3c80959e-748f-11e6-8885-81dc585a6002.png)

phoebe2 potentials computed with:

`
import libphoebe
import numpy as np
import matplotlib.pyplot as plt

d, V, p = np.loadtxt('[potentials.txt](https://github.com/phoebe-project/phoebe2/files/458260/potentials.txt)', usecols=(0, 1, 3), unpack=True)

pots = []
for dist in d:
    pots.append(libphoebe.roche_Omega_at_vol(V[0], 1.0, 1.0, dist, 8.0))
pots = np.array(pots)

plt.xlabel('1/d')
plt.ylabel('Omega-OmegaWD')
plt.plot(1./d, pots-p, 'b-', lw=2)
plt.show()
`

The file potentials.txt comes from phoebe1 and it is attached to this issue. Finally, the recap of phoebe1 is attached ([volume.pdf](https://github.com/phoebe-project/phoebe2/files/458262/volume.pdf)).

**Comment by horvatm** [comment]
Suggest plotting relative error.

**Comment by aprsa** [comment]
Here it is. 
![relative](https://cloud.githubusercontent.com/assets/2669162/18312059/b6c015d2-74d5-11e6-9aef-28a937fd72f8.png)

**Comment by horvatm** [comment]
In the our version, we calculate potential and derivate w.r.t to Omega to precision 1e-12/2 and adjustment of Omega are done to precision 1e-12. Timing:

  choice = 1:  time[ms]= 10860.6607914 
  choice = 0:  time[ms]= 6701.51686668

With setting precision =1e-6 we get

  choice=1:time[ms]= 2348.23989868
  choice =0:time[ms]= **1229.57396507**

I guess this low precision calculation can be further optimized,

The old version at default precision around 1e-16:

  choice=1: time[ms]= 22456.8879604

``` python
import libphoebe
import numpy as np
import matplotlib.pyplot as plt
import time

d, V, p = np.loadtxt('potentials.txt', usecols=(0, 1, 3), unpack=True)

pots = []
choice=1

start = time.time()
if choice:
    
  for dist in d:
      pots.append(libphoebe.roche_Omega_at_vol(V[0], 1.0, 1.0, dist, 8.0, precision=1e-6))
else:
  
  Omega=8.0
  for dist in d:
      Omega=libphoebe.roche_Omega_at_vol(V[0], 1.0, 1.0, dist, Omega, precision=1e-6)
      pots.append(Omega)

end = time.time()

print "time[ms]=", 1000*(end-start)

pots = np.array(pots)

plt.xlabel('1/d')
plt.ylabel('Omega-OmegaWD')
plt.plot(1./d, p/pots-1, 'b-', lw=2)
plt.show()
```
