### ISSUE TITLE
disable features not included in beta release

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#74]
Disable all unsupported/untested features and allow enabling with a switch for developers/testers.  This switch could be a flag somewhere in the code or checking for the presence of some file in the source or home directory (which could be included in gitignore so it doesn't accidentally get committed).

Features to disable:
* triples and higher-order hierarchies
* dynamics_method='nbody'
* distortion_method='nbody'
* pulsations
* overcontacts (overcontact=True switch in classmethods as well as building envelope mesh)
* misaligned binaries (not even implemented - will need to raise error if not aligned)
* lc_method='analytical'
* ETVs (and hide compute options)
* IFMs
* photodynam backend
* jktebop backend
* alternate plotting backends

Also will need to remove these features from the tutorials/example scripts that are packaged for beta-release - or at the least include a warning and mention that they are disabled.

**Comment by kecnry** [comment]
Developer mode is now disabled by default and can be enabled by the following:

`touch ~/.phoebe_devel_enabled`

This is nice because it is lightweight and doesn't involve changing the source and risking accidentally committing.... but the filename can be up for debate if anyone has objections.

**Comment by aprsa** [comment]
This certainly works, but it might be more elegant to provide a switch to setup.py, something like --enable-developer-mode?
