### ISSUE TITLE
Write release document

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#75]
The document needs to contain:

* supported physics w.r.t. phoebe1
* unsupported physics w.r.t. phoebe1
* unsupported convenience w.r.t. phoebe1 (GUI, fitting)
* any caveats
* future release schedule (at least tentative)
* testing
* bug/feature/... reporting instructions
* links to documentation/tutorials/online help
* how to get in touch
* how to contribute
* how to reference phoebe in the literature
* etc etc

**Comment by kecnry** [comment]
Some of this is already included in the docs index (https://github.com/phoebe-project/phoebe2/blob/master/docs/index.rst), and anything that isn't should be added there.  If we want a separate text document with just this information, that's fine with me too.
