### ISSUE TITLE
Phoebe 2.4.11 build failure on Python 3.11.4

### ISSUE THREAD

**Issue by spencel9** [phoebe-project/phoebe2#770]
Phoebe fails to build in venv with Python 3.11.4.

```
Collecting phoebe
  Downloading phoebe-2.4.11.tar.gz (77.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.7/77.7 MB 42.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Numpy is needed for running and building of PHOEBE
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by spencel9** [comment]
Numpy is installed

`Name: numpy
Version: 1.24.4
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD-3-Clause
Location: /Users/lindsayspence/phoebevenv/lib/python3.8/site-packages
Requires:
Required-by:`

**Comment by aprsa** [comment]
@spencel9, can you please try the 2.4.12 build? We replaced the build system and I'm hoping that this is resolved.

**Comment by kecnry** [comment]
This _should_ be fixed now, if anyone runs into this same problem after 2.4.12, please re-open this issue or create a new one.
