### ISSUE TITLE
near-critical system fails Omega_at_vol

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#773]
To reproduce:

```
import numpy as np
import libphoebe
libphoebe.roche_misaligned_Omega_at_vol(0.011969472802319008, 0.3664, 11.66, 1, np.array([ 7.84353845e-18, -2.39435968e-34,  1.00000000e+00]))
```

setting the spin axis to `[0., 0., 1.]` succeeds and returns `8.93888521685666`.

We can add logic to pass exactly `[1, 0, 0]` instead of computing the spin vector (sounds easy, but that part of the code doesn’t technically have access to the pitch/yaw, so it will take some thinking), but in theory there could also be an intentionally misaligned system with similar inputs so handling these cases in libphoebe might also be beneficial.

**Comment by horvatm** [comment]
By setteing verbosity to higher level

`libphoebe.setup_verbosity(4)`

it becomes clear that this is almost singular, which is mathematically difficult to handle.

In which direction this should be fixed? If somebody enters wrong spin (a) should it map to something meaningful or (b) should libphoebe just say that we don't deal with such singular cases?

**Comment by kecnry** [comment]
Phoebe is passing this spin (not the user), probably just from floating point imprecision.  For the case of no misalignment, we can hardcode a `[0, 0, 1]` input to libphoebe easily enough, but I wonder if this will just crop up elsewhere for the misaligned-case if the spin vector isn't perfectly normalized (in which case I'd say libphoebe needs to be more forgiving or we need to add logic before calling libphoebe to correct the inputs)?

**Comment by kecnry** [comment]
@horvatm - have you had any chance to look into this any more?

**Comment by horvatm** [comment]
I am almost sure that I corrected this for the  summer workshop.

**Comment by kecnry** [comment]
In 2.4.16, I am now getting `TypeError: roche_misaligned_Omega_at_vol::Maximum number of iterations exceeded`

**Comment by horvatm** [comment]
I see. I fixed a related issue. How do you want it fixed ?

**Comment by kecnry** [comment]
What are the options?  See https://github.com/phoebe-project/phoebe2/issues/773#issuecomment-1696261428 (either libphoebe or phoebe should probably handle the mapping to ensure a properly normalized/accepted spin vector).

**Comment by horvatm** [comment]
Should I make a new branch and then you merge the changes ?

**Comment by kecnry** [comment]
yes, please make a PR to `bugfix-2.4.16`
