### ISSUE TITLE
Sort out phasing w.r.t. all possible periods

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#81]
The frontend needs to be able to seamlessly phase on any period provided in the code: orbital, rotational, pulsational, ...

Once this is done, revisit the qualifier name for individual periods: should they all be called 'period' and their component identifies them uniquely, or should the qualifiers themselves be different (period, prot, ...).

**Comment by aprsa** [comment]
commit d92b5afd3fda55f46c8f160b2562dd484e278912 fixes phasing w.r.t. dpdt.

**Comment by kecnry** [comment]
phaseshift still needs to be automatically enabled for models and disabled for datasets during plotting (likely broken at the moment(
