### ISSUE TITLE
consider renaming orientation parameters for stars

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#83]
Currently constraints keep stars aligned and the constrained parameters don't really do anything.  Once misaligned orbits are supported, we will need to finalize these parameter names.

For aligned systems, these will be directly constrained to be equivalent to incl and long_an of the parent orbit.  So do we call these 'incl' and 'long_an' or 'pitch' and 'yaw'?

**Comment by kecnry** [comment]
see ef585a4a4263a7dc45973aa73d2d8da7a9e50327 for current implementation of pitch@star, yaw@star, incl@star, long_ae@star (this name still up for debate)

**Comment by aprsa** [comment]
I think long_ae is the worst of all worlds. While long_an doesn't really mean anything for single stars, it makes sense at least in the context of orbital long_an. While I am not happy with long_an, I find it better than long_ae (ascending equator).
