### ISSUE TITLE
Warning when using run-compute()

### ISSUE THREAD

**Issue by karanbt** [phoebe-project/phoebe2#908]
### Discussed in https://github.com/phoebe-project/phoebe2/discussions/805

<div type='discussions-op-text'>

<sup>Originally posted by **minnieliao** December  7, 2023</sup>
Hi, I was following Phoebe's tutorials on the compute section. I'm encountering an error similar to the one posted here when using run_compute() on my default binary bundle.

here is my code 
```
import phoebe 

phoebe.download_passband("Johnson:V", content=None, local=True, gzipped=None)

b = phoebe.default_binary()

b.add_dataset('lc', compute_times=phoebe.linspace(0,1,51), dataset='lc01')
b.add_dataset('rv', compute_times=phoebe.linspace(0,1,21), dataset='rv01')

b.run_compute()
```

The error I have been getting is: **/home/karanbt/miniconda3/envs/astro/lib/python3.11/site-packages/astropy/io/fits/file.py:456: AstropyUserWarning: File may have been truncated: actual file length (294912) is smaller than the expected size (2165760)
  warnings.warn( 
TypeError: buffer is too small for requested array**

However, despite downloading the passband and upgrading to the latest package versions, it did not work for me. I would appreciate it if someone could assist me with this.

Thanks.</div>

**Comment by karanbt** [comment]
Is it possible that the issue is caused by the FITS file generated consuming more memory than the memory allocated to WSL on my system? The other day, I was able to run the notebook on Google Colab without encountering any errors.

**Comment by aprsa** [comment]
I don't think so - I imagine that we would get an out-of-memory exception in that case, not a silent truncation. This seems to be a corrupted passband file while being downloaded from phoebe servers. This happens infrequently, but still frequently enough that it shows up. What happens if you try to load the passband directly?

```
pb = phoebe.get_passband('Johnson:V')
print(pb.content)
```

**Comment by karanbt** [comment]
This is after explicitly downloading passband Johnson:V right after importing Phoebe  

```
['ck2004:Inorm', 'phoenix:ld', 'phoenix:Inorm', 'ck2004:ldint', 'extern_atmx:Inorm', 'blackbody:Inorm', 'extern_planckint:Inorm', 'ck2004:ld', 'phoenix:ldint', 'phoenix:Imu', 'ck2004:Imu']

```
One of my colleagues suggested that the issue might be related to memory allocation, as I am using an old system with 4GB of RAM and WSL can only utilize half of the system's RAM.

**Comment by aprsa** [comment]
I still don't think this has to do with the amount of RAM; passband tables are of the order of 15MB in size. Can you please show me the output of `ls -lh ~/.phoebe/atmospheres/tables/passbands`? If you don't have any passbands in there, can you find the same directory in your install path, either `/usr/local/` if a global install, or `/path/to/venv/lib` if in a venv?

**Comment by aprsa** [comment]
Also, can you check that the bolometric passband is loading correctly?
```
pb = phoebe.get_passband('Bolometric:900-40000')
print(pb.content)
```
