### ISSUE TITLE
issue with computing ck2004 response and intensities

### ISSUE THREAD

**Issue by srkennelly** [phoebe-project/phoebe2#909]
Hi there! 

 I was setting up some custom passbands and I'm having an issue with the `pb.compute_ck2004_response`  and `pb.compute_ck2004_intensities` functions.  Usually, these take some time to run and, with `verbose=True`, I get a % completion.  Today, however, the cells in the Jupyter Notebook run and finish immediately, and I get no %completion output.  When I try to plot the blackbody response after computing the ck2004 response, the atmosphere parameters are out of bounds (because nothing was computed).

I use an external drive to store my ck2004 tables.  Usually, removing this results in an error with the functions (as expected).  Now, the cells will still run immediately and supposedly complete computing the ck2004 response and intensities.

I did also try to use the colab notebook in the tutorial to check if the functions worked there, but there seems to be an issue with numpy so I've been unable to get anything to run.

Is there anything that I can do to fix this?  I have restarted my machine, which hasn't helped unfortunately.  I also ran some of my other notebooks where I import Phoebe and everything else runs as normal.

Thanks!

**Comment by aprsa** [comment]
It sounds to me like phoebe can't find the atmosphere files correctly on your external hard drive. Has anything changed, such as file permissions or mount point specs or directory structure or phoebe version?

**Comment by srkennelly** [comment]
I went through all of these options - checking my python packages and my Phoebe version was correct - with my supervisor and eventually, we found the issue.  Despite everything being the same as last Friday, when the notebooks last ran, the external drive had decided to rename itself.  Correcting that fixed the issue, and everything runs as normal now.

Thank you for your help!
