### ISSUE TITLE
Run_checks() always FAIL

### ISSUE THREAD

**Issue by Randolph03** [phoebe-project/phoebe2#916]
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/75882381-b242-45ec-9b08-5b6330740404)
I'm trying to run Nelder-Mead solver, but it's always stuck like this..., If I force it to run, it will simply become like this:
![messageImage_1719756527607](https://github.com/phoebe-project/phoebe2/assets/89331160/85051662-9874-4c57-89ba-7e9fe57a90a6)

Addendum for when I check the constraint:
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/7e6ee125-776e-44df-b252-673cac58ad87)
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/3b904681-38ee-4aa5-9f25-424688c2a2fc)

**Comment by Randolph03** [comment]
for the dataset scaling, I think it's because I set the pblum into data-set scaled, but for the interchanging esinw & ecosw with the ecc & per0, I haven't figured out the reason yet

**Comment by kecnry** [comment]
Can you please include the full text of the checks report?  They likely say which solver/solution they actually affect (these particular check failures will not affect calls to `run_compute`).  If you want to adopt the proposed values for those parameters from that solution, you'll just need to manually flip the constraints first.

**Comment by Randolph03** [comment]
Thank you! It indeed didn't affect the run_compute and I finally can got the solution from nm. I think the problem for my running previously is because I set the pblum into dataset-scaled. I have changed it into component-coupled and set it so that the pblum@primary is also one of the fitted parameter and it works 👍  

While I still didn't understand though why does it ask for me to flip my constraint (from ecc and per0 into esinw and ecosw), and when I did flip the constraint, it asked me to flip it back again (from esinw and ecosw inti ecc and per0), but aas long as it can run the compute, all well is well 😅

Once again, thank you for the response, much appreciated

**Comment by kecnry** [comment]
Each of the estimators propose values for different parameters, and when those don't match your current parameterization (the way you have the constraints set), they can only automatically translate the parameters to your parameterization if there is no ambiguity.  If there is any ambiguity, then you would get this message when trying to adopt the results forcing you to decide which parameter(s) should _instead_ by set (and which should remain fixed).

For the case of esinw _and_ ecosw, there wouldn't technically be ambiguity, but PHOEBE isn't currently smart enough to realize that those two sets of equations are coupled together and therefore which sets e and which sets w ultimately won't matter.
