### ISSUE TITLE
export NM_solver for spot 

### ISSUE THREAD

**Issue by Randolph03** [phoebe-project/phoebe2#920]
I don't understand why is this happening at all, even though when doing run_solver, it work just fine
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/b1f42713-283c-4978-bfaf-561110830367)

The setup for the solver and export_solver 
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/396d14d3-eceb-4708-94e1-ffac0ddb5193)
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/61be8a2c-4ecc-4076-b2b9-3341efd01d65)
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/0f508c6b-3b34-402f-ab81-a01f4604ce09)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_13572\587935198.py in ?()
----> 1 b.export_solver('D:\\Kuliah\\TYC\\TRT_Estimator_Phoebe01_Binned_spot.py', 
      2                 solver='nm_solver',
      3                 compute='phoebe01',
      4                 maxiter=5000,

c:\Users\User\anaconda3\envs\phoebe_env\lib\site-packages\phoebe\frontend\bundle.py in ?(self, script_fname, out_fname, solver, solution, pause, autocontinue, import_from_older, log_level, **kwargs)
  13190         if use_server == 'compute':
  13191             use_server = self.get_value(qualifier='use_server', compute=self.get_value(qualifier='compute', solver=solver, context='solver', **_skip_filter_checks), context='compute', **_skip_filter_checks)
  13192 
  13193         solver, solution, compute, solver_ps = self._prepare_solver(solver, solution, from_export=True, **kwargs)
> 13194         script_fname, out_fname = self._write_export_solver_script(script_fname, out_fname, solver, solution, autocontinue, use_server, import_from_older, log_level, kwargs)
  13195 
  13196         if pause:
  13197             input("* optional:  call b.save(...) to save the bundle to disk, you can then safely close the active python session and recover the bundle with phoebe.load(...)\n"+

c:\Users\User\anaconda3\envs\phoebe_env\lib\site-packages\phoebe\frontend\bundle.py in ?(self, script_fname, out_fname, solver, solution, autocontinue, use_server, import_from_older, log_level, kwargs)
  13057         exclude_solvers = [s for s in self.solvers if s!=solver]
  13058         solver_ps = self.get_solver(solver=solver, **_skip_filter_checks)
  13059         if 'compute' in solver_ps.qualifiers:
  13060             compute = solver_ps.get_value(qualifier='compute', compute=kwargs.get('compute', None), default=[], **_skip_filter_checks)
> 13061             exclude_features = [feature for feature in self.features if not self.get_value(qualifier='enabled', feature=feature, compute=compute, **_skip_filter_checks)]
  13062         else:
  13063             exclude_features = []
  13064             exclude_contexts += ['feature', 'compute']

c:\Users\User\anaconda3\envs\phoebe_env\lib\site-packages\phoebe\frontend\bundle.py in ?(.0)
> 13061     def _write_export_solver_script(self, script_fname, out_fname, solver, solution, autocontinue, use_server, import_from_older, log_level, kwargs):
  13062         """
  13063         """
  13064         script = []

c:\Users\User\anaconda3\envs\phoebe_env\lib\site-packages\phoebe\parameters\parameters.py in ?(self, twig, unit, default, t, **kwargs)
   3291             kwargs['qualifier'], index = _extract_index_from_string(kwargs.get('qualifier'))
   3292         if kwargs.get('uniqueid', None):
   3293             kwargs['uniqueid'], index = _extract_index_from_string(kwargs.get('uniqueid'))
   3294 
-> 3295         param = self.get_parameter(twig=twig, **kwargs)
   3296 
   3297         # if hasattr(param, 'default_unit'):
   3298         # This breaks for constraint parameters

c:\Users\User\anaconda3\envs\phoebe_env\lib\site-packages\phoebe\parameters\parameters.py in ?(self, twig, **kwargs)
   3009         -------
   3010         * ValueError: if either 0 or more than 1 results are found
   3011             matching the search.
   3012         """
-> 3013         return self.get(twig=twig, **kwargs)

c:\Users\User\anaconda3\envs\phoebe_env\lib\site-packages\phoebe\parameters\parameters.py in ?(self, twig, check_visible, check_default, check_advanced, check_single, **kwargs)
   2656         # print "***", kwargs
   2657         ps = self.filter(twig=twig, **kwargs)
   2658         if not len(ps):
   2659             # TODO: custom exception?
-> 2660             raise ValueError("0 results found for twig: '{}', {}".format(twig, kwargs))
   2661         elif len(ps) != 1:
   2662             # TODO: custom exception?
   2663             raise ValueError("{} results found: {}".format(len(ps), ps.twigs))

ValueError: 0 results found for twig: 'None', {'qualifier': 'enabled', 'feature': 'spot01', 'compute': [], 'check_visible': False, 'check_default': False, 'check_advanced': False, 'check_single': False}

**Comment by Randolph03** [comment]
I'm sorry for frequently asking questions these days T.T

**Comment by kecnry** [comment]
This looks like it might be a bug.  Can you try removing `feature='spot01'` from your `b.add_solver` line and see if that helps anything?

If that doesn't, can you let us know what version of phoebe you're running and either send a copy of the bundle exported right before the `export_solver` line, or a short minimal script to reproduce (try to make a script as short as possible that still results in the same error message) and we'll try to look into it soon.

**Comment by Randolph03** [comment]
I'm using 2.4.14 ver. (I've tried removing the feature, and no change). 

Here is the bundle, alongside the script and dataset used:
[TRT_Estimator_Phoebe01_Binned_Spot.zip](https://github.com/user-attachments/files/16133803/TRT_Estimator_Phoebe01_Binned_Spot.zip)

I've tried running it once again using my own pc, focusing only on the spot; but it seems like NM doesn't optimize the spot at all?
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/5b8dce00-7c59-4786-a94f-331694bd625f)

Which kinda make sense since the constraint for nm_solver indeed doesn't include any paramaters relating to the spot
![image](https://github.com/phoebe-project/phoebe2/assets/89331160/f123a02c-a633-4598-8840-f1936fc95e2b)

Thank you for the help! Hopefully the problem is with my own code T.T

**Comment by kecnry** [comment]
This is a bug in phoebe and I have a pending fix (#922) that should be in the next bugfix release.  

The buggy logic in phoebe was triggered by passing `compute` to `export_solver` when there are features attached, and so you should be able to bypass it by _not_ passing `compute` and instead just setting the parameter value.  In your case, you already have `compute@nm_solver = 'phoebe01'`, so should be able to just skip the `compute = 'phoebe01'` argument in the call to `export_solver` and it should export successfully.

Sorry this took a while to track down!
