### ISSUE TITLE
incorporate robust meshing fallback

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#93]
Implement (into universe.py) the ability to fallback on libphoebe's new robust meshing

see #22 and #92 for relevant updates to libphoebe

**Comment by horvatm** [comment]
Closed by 92d1049.

**Comment by kecnry** [comment]
commit 34995176050ee3eab27c52390290c920a9231d90

note: this is currently implemented as the default (hardcoded) method and is not done as a fallback if the non-robust method fails.

**Comment by horvatm** [comment]
Perhaps I was to fast to close the issue. 

Did you perhaps mean that we should have an alternative to marching algorithm that we fall back to in case of trouble, as the current best marching algorithm, i.e. full version with fallback higher precision internally build in,  is still not bullet proof?
