### ISSUE TITLE
How can we save phases, fluxes, model, and the residuals as the text file?

### ISSUE THREAD

**Issue by kittipongwangnok** [phoebe-project/phoebe2#933]
How can we save the value phases, fluxes, model, and the residuals  that we used the value to plot in these commands:
_ = b.plot(kind='lc', model='orig_model', x='phases', y='fluxes', 
           s={'dataset': 0.005},
           marker={'dataset': '.'})
_ = b.plot(kind='lc', model='orig_model', x='phases', y='residuals', 
           z={'dataset': 0, 'model': 1},
           save='figure_posteriors_sample_from_lc.pdf', show=True)
<img width="878" alt="Screenshot 2567-09-01 at 1 45 17 PM" src="https://github.com/user-attachments/assets/5d9db8c3-6e64-43cc-835b-26b994262827">

**Comment by amiszuda** [comment]
You can access all the necessary values similarly as:
```
fluxes = b['fluxes@lc1@latest@model'].value
times  = b['times@lc1@latest@model'].value
resid = b.calculate_residuals(dataset='lc1')
```

Once you catch those, you can store them using, e.g. numpy savetext
