### ISSUE TITLE
Trouble installing PHOEBE on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by munkacsymj** [phoebe-project/phoebe2#938]
1. Python on Ubuntu 24.04 is managed via apt instead of pip, so created a virtual Python area. Used pip3 to install phoebe. Can go into python and "import phoebe" with no errors. (Shows up as version 2.4.14)
2. Downloaded Phoebe2-ui 1.0.1 Linux x64 tarball. Unpacked it. Added that directory to PATH variable.
3. Started phoebe. Received error message about chrome-sandbox not being setuid. Changed chrome-sandbox owner to root and set mode to 4755.
4. Ran phoebe again and received error message, "GPU process isn't usable. Goodbye." Seems this message comes from electron, and some users (other apps, not PHOEBE) find success using --no-sandbox.
5. Ran phoebe again with "-- no-sandbox".  The GUI seems to work, but it can't start up my server, because ...
6. I have no file named phoebe-server. Anywhere. So, clearly, I've missed a key step. What installation step creates this file and where does it get installed?

I'm not sure what to try next; looking for some advice...

**Comment by kecnry** [comment]
#929 should fix the `phoebe-server` issue and will be released in the next bugfix release (#907).  I'll check to see if we can get that officially released soon.

**Comment by munkacsymj** [comment]
Ah... your note was tremendously helpful. I pulled phoebe-server from github and ran it. Phoebe-gui would not connect to it. I started up wireshark and looked at the conversation between the gui and the server. It seems okay until Phoebe-gui sends a "GET /socket.io/?EIO=3&transport=websocket" which generates a console message from phoebe-server that says "The client is using an unsupported version of the Socket.IO or Engine.IO protocols". The connection then closes, and then the entire conversation restarts from the beginning. (And it loops like this forever.)

Using pip3 to get version info, phoebe-server is loading Flask-SocketIO version 5.3.7. (I don't know what version is being used by Phoebe-gui.) Does this sound like a version mismatch between phoebe-server and the phoebe-GUI? Is this something that would go away if I rebuilt Phoebe-gui from source?

**Comment by kecnry** [comment]
You can try, but there's a chance that the UI code has just become too outdated that it might cause you difficulties.  @matthiasfabry is working on updating the dependencies to bring it up to date (see https://github.com/phoebe-project/phoebe2-ui/issues/27) and might have a better feel for a potential timeline for that effort.

Until then, it sounds like the python package itself installed correctly if you're comfortable trying to use phoebe directly from python.  There are large set of [tutorials and example scripts](https://phoebe-project.org/docs/latest/tutorials) stepping through how to do that.

**Comment by matthiasfabry** [comment]
I hate to disappoint you, but it looks like updating the GUI will require a significant effort. A good amount of the code needs to be refactored because of API changes, not to mention changes in `phoebe-server` are also required, but I have to look into those yet.
At the moment I'm afraid using `phoebe` from python directly is the only way to properly interact with it.

**Comment by munkacsymj** [comment]
Thank you both, @matthiasfabry and @kecnry -- we'll shift to working with phoebe directly from Python.
