### ISSUE TITLE
reflection_method

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#95]
If there is a possibility of supporting multiple different methods for reflection (even if not ready to be included in 2.0b), we should switch from a bool parameter (refl) to a choice parameter (reflection_method) in time for the beta release or at least by 2.0 to avoid backwards compatibility issues down the road.

Proposed change:
refl = True/False -> reflection_method = \['none', 'wilson', 'horvat'\] (with 'horvat' perhaps moved to developer mode if not included in the paper)

See also #17 for a similar decision to be made with boosting/beaming.

---------------------

This also affects (again) the name of the "albedo" parameters.

Currently we have (required to sum to 1 by a constraint):
* frac_lost_bol
* frac_refl_bol
* frac_heating_bol (unsupported in 2.0b)
* frac_scattering_bol (unsupported in 2.0b)

but this is confusing, because reflection_method will affect both frac_refl and frac_heating (by necessity as they must be handled in parallel).  This will also cause problems when we need to split heating into different types of redistribution.

**alternative 1**:
* frac_lost_bol
* frac_refl_noredist_bol
* frac_refl_localredist_bol
* frac_refl_horizredist_bol
* frac_refl_globalredist_bol
* frac_scattering_bol

Here this is clear that reflection_method affects **all** reflection, whether redistribution occurs or not.

**alternative 2**:
* frac_lost_bol
* frac_refl_bol
  * frac_refl_noredist_bol
  * frac_refl_localredist_bol
  * frac_refl_horizredist_bol
  * frac_refl_globalredist_bol
* frac_scattering

This option is nice because it allows you to set the ratios in a tree structure by defining what ratio goes to *all* reflection and then breaking down that contribution... but makes for a mess in parameter names.

**alternative 3**:
* frac_lost_bol
* frac_refl_bol
* frac_reflredist_bol
* frac_scattering_bol

with compute options:
* reflection_method = ['none', 'wilson' , 'horvat']
* redistribution_method = ['local', 'horizontal', 'global']

This is perhaps the simplest option, but will **not** allow including multiple types of redistribution simultaneously.

--------------------

We don't need to decide on all the redistribution/heating names yet, but it would be a good idea to think ahead so that we don't need to change the name of the 'frac_refl_bol' parameter when we get around to implementing redistribution/heating.

**Comment by aprsa** [comment]
My favorite is alternative 2 (or something to similar extent).
