### ISSUE TITLE
Compute auxiliary files for all supported passbands

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#96]
This in itself is a straight-forward task; the computation functions have been optimized, but the problem is in model atmospheres: it turns out that the spectrum 2.76e program used to synthesize non-normalized intensities sometimes assigns flux 0.0 to some wavelengths, which in turn trips the spectral index calculation. This has been reported upstream and solved locally by interpolating across the zeros, but it does mean that all passbands need to be recomputed.

**Comment by aprsa** [comment]
Explanation for the zeros from upstream: "The problem that a few wavelengths (which are in the cores of very strong lines) go to zero is a consequence of 1) the assumption of pure absorption, and 2) a truncated stellar atmosphere model that does not go to small enough optical depths.  The problem could be largely solved by extrapolating the stellar atmosphere to smaller optical depths."

**Comment by aprsa** [comment]
Model atmospheres have been recomputed on the 900A-40um interval. These should be more robust than the previous set because they are computed with very high dispersion and then resampled to the 1A dispersion. It would take me another couple of days to recompute all passbands. Is it worth doing this for 2.0 or should we defer? Chances are this would break some of the nosetests because of precision issues.

**Comment by kecnry** [comment]
Do you think it would break nosetests because we'll have a decrease in precision?  Ultimately, with the exception of Bolometric and Johnson V, passbands are now separate, but I think we should converge them to their "final" state as quickly as possible, even if just to avoid any possible confusion.

**Comment by aprsa** [comment]
Pending on the resolution of #176.
