### ISSUE TITLE
Infinite recursion in constraints

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#97]
To reproduce:

b = phoebe.default_binary()
b.flip_constraint('mass@primary', 'sma@binary')
b.add_dataset('lc')

**Comment by kecnry** [comment]
may be related to #1

**Comment by kecnry** [comment]
I can no longer reproduce this.  Although there surely are situations where you can create long recursions in constraints, I think most cases are now caught.  I'm closing for now until/unless we see a case that causes problems.
