### ISSUE TITLE
Reflection using interpolation of intensities

### ISSUE THREAD

**Issue by horvatm** [phoebe-project/phoebe2#98]
Implementation of reflection effects that directly uses interpolation function as source of information about the intrinsic intensities instead of just the normal emergent intensity and using specific limb-darkening law.

**Comment by aprsa** [comment]
Let me know when you're ready to plug in the table lookup.

**Comment by aprsa** [comment]
We will not be able to do this robustly: we would need Imu for the bolometric ck2004 passband, which is limited to a narrow range of Teffs (T < 12000K), see #170. I suggest we defer this.

**Comment by horvatm** [comment]
I won't continue this path.
