### ISSUE TITLE
Typos in kwargs are not caught

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#99]
phoebe does not warn about named arguments that don't exist, i.e.

b.add_compute(this='that')

won't have any problems. This makes writing scripts error-prone since I could do something like:

b.add_compute(copmute='label') and this would not raise an error but obviously won't work as intended.

**Comment by kecnry** [comment]
This could be "fixed" by checking to make sure all kwarg keys are in bundle.qualifiers (or other accepted kwargs - for example plotting will need to also check a list of kwargs that are used throughout plotting or are acceptable to pass on to mpl).  That won't ensure that they're used, but will at least catch the typo case.

Let's try to get this in by beta if possible.

**Comment by kecnry** [comment]
run_compute now throws an error when trying to override parameters that don't exist yet (but would exist in the compute options)
