### ISSUE TITLE
the parameter issue in the emcee

### ISSUE THREAD

**Issue by tpos8** [phoebe-project/phoebe2#993]
Hi, I’m trying to fit my binary system’s light curve using PHOEBE with emcee. I’ve set the parameters from observations, but the results seem off. Could you share any tips to improve the fit?
Thanks a lot for your help!

![b3ceb0352b5c9c559ecd71474e3dcad](https://github.com/user-attachments/assets/de3c6d7f-c3fd-4a31-80d9-375e6ee5bc90)
![0b34247302e5505cc50d316f24bbf5f](https://github.com/user-attachments/assets/5500b760-4b55-4272-bfc2-e8255a03ee8a)
![b83c94c9bbad09df4b7b979291e226e](https://github.com/user-attachments/assets/dbb6cb63-6032-4f85-84b9-313efdf7e7da)
![eb22a23c4dc6090d9083c7e91691748](https://github.com/user-attachments/assets/91c33bf8-fa70-47a1-b30f-6146019e2001)

**Comment by kecnry** [comment]
What does your forward model look like when using the face-values and initializing distributions (something like `b.run_compute(sample_from='ball_around_guess', sample_num=10, model='init_model'); b.plot(model='init_model')`)?  

It looks like you're using `pblum_mode='absolute'`, but not accounting for the distance, so your flux-levels are likely nowhere near your observations and the parameters you're passing to emcee do not have the freedom to account for that offset.  We strongly suggest making sure that your model roughly resembles your observations (by hand and/or using estimators and optimizers, etc) _before_ using MCMC.

**Comment by tpos8** [comment]
> 当使用 face-values 和初始化分布时（类似于 ），你的 forward model 是什么样子的？`b.run_compute(sample_from='ball_around_guess', sample_num=10, model='init_model'); b.plot(model='init_model')`
> 
> 看起来你正在使用 ，但没有考虑距离，所以你的通量水平可能远不接近你的观察值，你传递给 emcee 的参数没有自由来考虑这个偏移量。我们强烈建议在使用 MCMC _之前_，确保您的模型与您的观察结果大致相似（手动和/或使用估计器和优化器等）。`pblum_mode='absolute'`

Yeah, I tried to use phoebe fit with my TESS observation flux, the phoebe program could fit the shape of flux but could not fit flux with the same order of magnitude. So, I think this is the main reason to impact the result of emcee, I used this method to compare the TESS flux with the phoebe fit flux `phoebe_fit = phoebe_fit*np.median(TESS_flux)/np.median(phoebe_fit）`

**Comment by tpos8** [comment]
The first image is the original observation flux, second image is the phoebe fit with this code `b.run_compute(sample_from='ball_around_guess', sample_num=20, model='init_from_model');_ = b.plot(dataset='lc01', x='phases', marker={'dataset': '.'}, model='init_from_model', show=True)`
![e617abdd28ca56eb9e8bf6f878ee497](https://github.com/user-attachments/assets/2a4936f6-8342-4672-a4cb-1f3f7dbed2d8)
![37544c10ce3b2c88de89cde8186dc8d](https://github.com/user-attachments/assets/f5d28d51-9cea-4774-ba8a-2e19b541ebe2)

**Comment by kecnry** [comment]
From that last plot, it looks like your model is orders of magnitude off in scale from your observations - you definitely will want to fix this before starting an MCMC run as phoebe does not know about your manual rescaling outside of phoebe. See the [tutorial on passband luminosity](https://phoebe-project.org/docs/latest/tutorials/pblum) for more details.

**Comment by tpos8** [comment]
> From that last plot, it looks like your model is orders of magnitude off in scale from your observations - you definitely will want to fix this before starting an MCMC run as phoebe does not know about your manual rescaling outside of phoebe. See the [tutorial on passband luminosity](https://phoebe-project.org/docs/latest/tutorials/pblum) for more details.

Thank for your help!!!
